// Package parity's change journal counts "files changed since last sync"
// per data disk without walking or stat'ing anything (Q13, doc 02 §2):
// hoservad places one FAN_MARK_FILESYSTEM mark per disk and records the
// create/modify/delete/rename events the kernel pushes for it. Counting
// never wakes a disk — every event this journal ever sees was already
// generated by a write that woke it on its own (doc 08 §1) — and nothing
// in this file runs on a timer (CLAUDE.md).
//
// Spike S7 (doc 08 §7) validated the exact mechanism this implements: a
// mark per disk, distinct-(directory-FID, name)-pair counting as the
// fallback identity when a full path cannot be resolved (this lab's own
// container lacks CAP_DAC_READ_SEARCH; a production daemon running as
// root is expected to resolve real paths but that is unconfirmed, S7's
// own residual risk), a listener restart and a filesystem remount both
// losing events silently, and queue overflow needing to be surfaced as
// "incomplete", never folded into an exact-looking number.
package parity

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"time"
)

// ChangeKind is the kind of filesystem change one recorded journal entry
// represents.
type ChangeKind int

const (
	ChangeCreate ChangeKind = iota
	ChangeDelete
	ChangeModify
	ChangeAttrib
	ChangeCloseWrite
	ChangeRenameFrom
	ChangeRenameTo
)

func (k ChangeKind) String() string {
	switch k {
	case ChangeCreate:
		return "create"
	case ChangeDelete:
		return "delete"
	case ChangeModify:
		return "modify"
	case ChangeAttrib:
		return "attrib"
	case ChangeCloseWrite:
		return "close_write"
	case ChangeRenameFrom:
		return "rename_from"
	case ChangeRenameTo:
		return "rename_to"
	default:
		return "unknown"
	}
}

// ChangeEvent is one decoded fanotify event for one disk's mark.
type ChangeEvent struct {
	Kind ChangeKind
	// ID identifies the changed directory entry across events on this
	// disk, so the same entry changing twice counts once: spike S7's
	// validated (directory-FID, reported-name) pair, opaque and never
	// itself shown to a user.
	ID string
	// Name is the changed entry's own name, as fanotify reported it —
	// what "files changed ... by name" (doc 02 §2, §4) falls back to
	// when Path could not be resolved.
	Name string
	// Path is the resolved absolute path, when the Watcher could
	// resolve one (needs CAP_DAC_READ_SEARCH — unconfirmed by S7, doc 08
	// §7's own residual risk). Empty when it could not be; a caller must
	// always be able to fall back to Name.
	Path string
}

// StreamEvent is one item a Stream delivers. Exactly one of Change or
// Overflow is meaningful, matching one fanotify_event_metadata record
// off the wire.
type StreamEvent struct {
	Change   ChangeEvent
	Overflow bool
}

// Watcher is the system-touching capability a Journal needs: placing one
// FAN_MARK_FILESYSTEM mark per data disk and delivering the events it
// generates. It sits behind this interface, with FakeWatcher alongside
// it, so Journal and everything above it are fully testable without
// CAP_SYS_ADMIN (CLAUDE.md: every system-touching subsystem sits behind
// a package interface with a scriptable fake).
type Watcher interface {
	// Watch places a FAN_MARK_FILESYSTEM mark on mountpoint and returns
	// a Stream delivering its events until the Stream is closed or ctx
	// is done. Watch never polls: every Stream.Next call blocks on a
	// syscall until the kernel has something to deliver.
	Watch(ctx context.Context, mountpoint string) (Stream, error)
}

// Stream delivers one mounted filesystem's fanotify events, batched the
// way the kernel itself delivers them: one Next call corresponds to one
// underlying read(2), which can return many queued events at once. A
// Journal persists its state once per batch rather than once per event.
type Stream interface {
	// Next blocks until at least one event or overflow marker is ready,
	// or returns a non-nil error once the stream is done (Close called,
	// ctx cancelled, or a read failure). A caller must not call Next
	// again after a non-nil error.
	Next() ([]StreamEvent, error)
	Close() error
}

// ChangeSummary is what Summary reports for one disk.
type ChangeSummary struct {
	// Count is the number of distinct entries recorded since the last
	// ResetSince — shown as approximate through the API (doc 02 §2's
	// amber indicator); the exact number is only ever `snapraid diff`,
	// run immediately before a sync.
	Count int
	// Overflowed is true once this disk's fanotify queue has dropped
	// events (FAN_Q_OVERFLOW, spike S7) since the last ResetSince — Count
	// is then known-incomplete, not merely approximate, and a caller
	// must present it that way (Q13).
	Overflowed bool
	// Listening is false when this disk currently has no live mark —
	// never armed, or a remount silently stopped delivery (S7) and Rearm
	// hasn't run since. Count is then not just approximate but stale:
	// changes since Listening went false are invisible to it.
	Listening bool
}

// ChangedFile is one entry the journal's Files reports for a disk: what
// "files changed since last sync on disk N, by name" (doc 02 §2, §4)
// resolves to.
type ChangedFile struct {
	Name string
	Path string // "" when unresolved; callers fall back to Name.
	Kind ChangeKind
	At   time.Time
}

// ErrDiskNotTracked is returned by every Journal method keyed by diskID
// when AddDisk was never called for it (or RemoveDisk already was).
var ErrDiskNotTracked = errors.New("parity: journal: disk not tracked")

// Clock lets tests control the timestamps a Journal records.
type Clock func() time.Time

// defaultJournalPersistInterval bounds how often readLoop writes a disk's
// snapshot to disk during a burst of fanotify batches (e.g. extracting an
// archive): every batch still updates the in-memory state immediately —
// Summary and Files are never stale — but the fsync'd snapshot write is
// skipped for a batch that lands within this interval of the last one
// actually written, still driven by real events rather than a timer. A
// clean stop (RemoveDisk, Rearm, Close, ctx cancelled) always flushes any
// batch this skipped before the read loop exits, so only a genuine crash
// mid-burst can lose more than the usual restart gap (Q13's own
// documented gap) — never an ordinary stop.
const defaultJournalPersistInterval = 500 * time.Millisecond

// Journal tracks, per data disk, distinct filesystem changes observed
// since the last successful sync (doc 02 §2, Q13). It is a passive
// listener only: every disk's state changes exactly when a Watcher
// delivers an event, never on a timer.
type Journal struct {
	watcher         Watcher
	root            string // snapshot directory; "" disables persistence
	now             Clock
	persistInterval time.Duration

	mu    sync.Mutex
	disks map[string]*diskJournal
}

// NewJournal returns a Journal that watches through watcher and persists
// each disk's state as a small JSON snapshot under root. root may be
// empty to disable persistence (e.g. in tests that don't need it to
// survive a restart) — internal/store is out of scope for this package,
// so this is its own small file-based mechanism, in the spirit of
// internal/config's Generator, rather than a store table.
func NewJournal(watcher Watcher, root string) *Journal {
	return &Journal{
		watcher:         watcher,
		root:            root,
		now:             time.Now,
		persistInterval: defaultJournalPersistInterval,
		disks:           make(map[string]*diskJournal),
	}
}

type diskJournal struct {
	mountpoint string

	mu            sync.Mutex
	cancel        context.CancelFunc
	stream        Stream
	done          chan struct{}
	entries       map[string]ChangedFile
	order         []string // insertion order of entries.
	overflowed    bool
	listening     bool
	persistErr    error
	dirty         bool      // true when in-memory state has changed since the last write to disk.
	lastPersistAt time.Time // zero until the first successful (or attempted) persist.
}

// AddDisk starts tracking diskID at mountpoint: it arms a mark and, if a
// prior snapshot exists under this Journal's root, resumes from it
// rather than starting empty — a hoservad restart must not silently
// forget changes that happened before it, even though it does lose the
// events that happen during the restart itself (Q13's own documented
// gap; Rearm is what a caller uses once it detects that gap has closed).
func (j *Journal) AddDisk(ctx context.Context, diskID, mountpoint string) error {
	j.mu.Lock()
	if _, exists := j.disks[diskID]; exists {
		j.mu.Unlock()
		return fmt.Errorf("parity: journal: disk %q already added", diskID)
	}
	j.mu.Unlock()

	dj := &diskJournal{mountpoint: mountpoint, entries: make(map[string]ChangedFile)}
	if j.root != "" {
		snap, err := loadSnapshot(j.root, diskID)
		if err == nil {
			dj.entries, dj.order = snap.entries()
			dj.overflowed = snap.Overflowed
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("parity: journal: loading snapshot for disk %q: %w", diskID, err)
		}
	}

	if err := j.arm(ctx, dj); err != nil {
		return err
	}

	j.mu.Lock()
	j.disks[diskID] = dj
	j.mu.Unlock()

	go j.readLoop(diskID, dj)
	return nil
}

// Rearm re-issues diskID's mark after a caller has detected that its
// filesystem was remounted — the one case a mark cannot survive on its
// own (spike S7: a remount silently stops event delivery, with no error
// and no way for this package to notice it unprompted). Every change
// already recorded is kept; only listening resumes, since the files that
// changed before the remount are still unsynced.
func (j *Journal) Rearm(ctx context.Context, diskID string) error {
	dj := j.disk(diskID)
	if dj == nil {
		return fmt.Errorf("%w: %s", ErrDiskNotTracked, diskID)
	}
	j.disarm(dj)
	if err := j.arm(ctx, dj); err != nil {
		return err
	}
	go j.readLoop(diskID, dj)
	return nil
}

func (j *Journal) arm(ctx context.Context, dj *diskJournal) error {
	wctx, cancel := context.WithCancel(ctx)
	stream, err := j.watcher.Watch(wctx, dj.mountpoint)
	if err != nil {
		cancel()
		return fmt.Errorf("parity: journal: watching %s: %w", dj.mountpoint, err)
	}

	dj.mu.Lock()
	dj.cancel = cancel
	dj.stream = stream
	dj.listening = true
	dj.done = make(chan struct{})
	dj.mu.Unlock()
	return nil
}

// disarm stops dj's current stream, if any, and waits for its read loop
// to exit, so a caller never has two read loops racing on the same
// diskJournal.
func (j *Journal) disarm(dj *diskJournal) {
	dj.mu.Lock()
	cancel := dj.cancel
	stream := dj.stream
	done := dj.done
	dj.mu.Unlock()

	if cancel != nil {
		cancel()
	}
	if stream != nil {
		_ = stream.Close()
	}
	if done != nil {
		<-done
	}
}

func (j *Journal) readLoop(diskID string, dj *diskJournal) {
	defer close(dj.done)
	for {
		batch, err := dj.stream.Next()
		if err != nil {
			dj.mu.Lock()
			dj.listening = false
			dj.mu.Unlock()
			j.flushIfDirty(diskID, dj)
			return
		}
		if len(batch) == 0 {
			continue
		}

		dj.mu.Lock()
		for _, ev := range batch {
			if ev.Overflow {
				dj.overflowed = true
				continue
			}
			c := ev.Change
			if _, seen := dj.entries[c.ID]; !seen {
				dj.order = append(dj.order, c.ID)
			}
			dj.entries[c.ID] = ChangedFile{Name: c.Name, Path: c.Path, Kind: c.Kind, At: j.now()}
		}
		dj.dirty = true
		due := dj.lastPersistAt.IsZero() || j.now().Sub(dj.lastPersistAt) >= j.persistInterval
		dj.mu.Unlock()

		if due {
			j.persist(diskID, dj)
		}
	}
}

// persist writes dj's current state to disk unconditionally, recording
// when it did so (for the next batch's debounce check) and clearing
// dirty. A no-op when this Journal has no root (persistence disabled).
func (j *Journal) persist(diskID string, dj *diskJournal) {
	if j.root == "" {
		return
	}
	dj.mu.Lock()
	snap := dj.snapshotLocked(j.now())
	dj.mu.Unlock()

	err := writeSnapshotAtomic(j.root, diskID, snap)

	dj.mu.Lock()
	dj.persistErr = err
	dj.lastPersistAt = j.now()
	dj.dirty = false
	dj.mu.Unlock()
}

// flushIfDirty persists dj one last time if readLoop debounced away a
// batch that never got its own write before the stream ended — a clean
// stop (RemoveDisk, Rearm, Close, ctx cancelled) must never leave the
// on-disk snapshot behind the in-memory state it already reflects.
func (j *Journal) flushIfDirty(diskID string, dj *diskJournal) {
	dj.mu.Lock()
	dirty := dj.dirty
	dj.mu.Unlock()
	if dirty {
		j.persist(diskID, dj)
	}
}

// RemoveDisk stops tracking diskID and releases its mark.
func (j *Journal) RemoveDisk(diskID string) error {
	j.mu.Lock()
	dj, ok := j.disks[diskID]
	if ok {
		delete(j.disks, diskID)
	}
	j.mu.Unlock()
	if !ok {
		return fmt.Errorf("%w: %s", ErrDiskNotTracked, diskID)
	}
	j.disarm(dj)
	return nil
}

// Close stops every tracked disk.
func (j *Journal) Close() error {
	j.mu.Lock()
	ids := make([]string, 0, len(j.disks))
	for id := range j.disks {
		ids = append(ids, id)
	}
	j.mu.Unlock()
	for _, id := range ids {
		_ = j.RemoveDisk(id)
	}
	return nil
}

func (j *Journal) disk(diskID string) *diskJournal {
	j.mu.Lock()
	defer j.mu.Unlock()
	return j.disks[diskID]
}

// Summary reports diskID's approximate change count since its last reset
// (doc 02 §2's amber indicator, "shown as approximate through the API").
func (j *Journal) Summary(diskID string) (ChangeSummary, error) {
	dj := j.disk(diskID)
	if dj == nil {
		return ChangeSummary{}, fmt.Errorf("%w: %s", ErrDiskNotTracked, diskID)
	}
	dj.mu.Lock()
	defer dj.mu.Unlock()
	return ChangeSummary{
		Count:      len(dj.entries),
		Overflowed: dj.overflowed,
		Listening:  dj.listening,
	}, nil
}

// Files answers "files changed since last sync on disk N, by name",
// oldest-recorded first.
func (j *Journal) Files(diskID string) ([]ChangedFile, error) {
	dj := j.disk(diskID)
	if dj == nil {
		return nil, fmt.Errorf("%w: %s", ErrDiskNotTracked, diskID)
	}
	dj.mu.Lock()
	defer dj.mu.Unlock()
	return dj.filesLocked(), nil
}

// Snapshot returns diskID's ChangeSummary and change list as they stood
// at one instant — the pairing FixPendingFiles needs (doc 03 §3.5's
// guided-fix pre-check): Summary and Files each take dj.mu independently,
// so an entry recorded between two separate calls could make Count or
// Overflowed describe an earlier moment than Files does. Snapshot takes
// dj.mu once and builds both from it, so a caller never sees a count or
// completeness state that doesn't match the list it's shown beside.
func (j *Journal) Snapshot(diskID string) (ChangeSummary, []ChangedFile, error) {
	dj := j.disk(diskID)
	if dj == nil {
		return ChangeSummary{}, nil, fmt.Errorf("%w: %s", ErrDiskNotTracked, diskID)
	}
	dj.mu.Lock()
	defer dj.mu.Unlock()
	summary := ChangeSummary{
		Count:      len(dj.entries),
		Overflowed: dj.overflowed,
		Listening:  dj.listening,
	}
	return summary, dj.filesLocked(), nil
}

// filesLocked builds Files's own return value; the caller must hold
// dj.mu.
func (dj *diskJournal) filesLocked() []ChangedFile {
	out := make([]ChangedFile, 0, len(dj.order))
	for _, id := range dj.order {
		out = append(out, dj.entries[id])
	}
	return out
}

// PersistError reports the error from diskID's most recent attempt to
// persist its snapshot, if any — nil means the last attempt (if there
// was one) succeeded. A caller that wires this journal into the
// dashboard should surface a non-nil PersistError, since it means a
// hoservad restart before the next successful persist would lose more
// than the usual restart gap.
func (j *Journal) PersistError(diskID string) error {
	dj := j.disk(diskID)
	if dj == nil {
		return fmt.Errorf("%w: %s", ErrDiskNotTracked, diskID)
	}
	dj.mu.Lock()
	defer dj.mu.Unlock()
	return dj.persistErr
}

// ResetSince clears diskID's recorded changes. Doc 02 §2: "count reset
// at each successful sync" — this package never drives a sync itself
// (that is SnapraidEngine.Sync, #28); a caller invokes ResetSince once it
// has confirmed a sync covering diskID succeeded.
func (j *Journal) ResetSince(diskID string) error {
	dj := j.disk(diskID)
	if dj == nil {
		return fmt.Errorf("%w: %s", ErrDiskNotTracked, diskID)
	}

	dj.mu.Lock()
	dj.entries = make(map[string]ChangedFile)
	dj.order = nil
	dj.overflowed = false
	dj.mu.Unlock()

	if j.root == "" {
		return nil
	}
	j.persist(diskID, dj)
	dj.mu.Lock()
	err := dj.persistErr
	dj.mu.Unlock()
	return err
}

func (dj *diskJournal) snapshotLocked(now time.Time) journalSnapshot {
	entries := make([]snapshotEntry, 0, len(dj.order))
	for _, id := range dj.order {
		cf := dj.entries[id]
		entries = append(entries, snapshotEntry{ID: id, Name: cf.Name, Path: cf.Path, Kind: cf.Kind, At: cf.At})
	}
	return journalSnapshot{
		Mountpoint: dj.mountpoint,
		Entries:    entries,
		Overflowed: dj.overflowed,
		SavedAt:    now,
	}
}

// journalSnapshot is the on-disk shape of one disk's persisted journal
// state (see doc comment on NewJournal for why this package persists its
// own small file rather than a store table).
type journalSnapshot struct {
	Mountpoint string          `json:"mountpoint"`
	Entries    []snapshotEntry `json:"entries"`
	Overflowed bool            `json:"overflowed"`
	SavedAt    time.Time       `json:"saved_at"`
}

type snapshotEntry struct {
	ID   string     `json:"id"`
	Name string     `json:"name"`
	Path string     `json:"path,omitempty"`
	Kind ChangeKind `json:"kind"`
	At   time.Time  `json:"at"`
}

func (s journalSnapshot) entries() (map[string]ChangedFile, []string) {
	entries := make(map[string]ChangedFile, len(s.Entries))
	order := make([]string, 0, len(s.Entries))
	for _, e := range s.Entries {
		entries[e.ID] = ChangedFile{Name: e.Name, Path: e.Path, Kind: e.Kind, At: e.At}
		order = append(order, e.ID)
	}
	return entries, order
}

func snapshotPath(root, diskID string) string {
	return filepath.Join(root, diskID+".json")
}

func loadSnapshot(root, diskID string) (journalSnapshot, error) {
	data, err := os.ReadFile(snapshotPath(root, diskID))
	if err != nil {
		return journalSnapshot{}, err
	}
	var snap journalSnapshot
	if err := json.Unmarshal(data, &snap); err != nil {
		return journalSnapshot{}, fmt.Errorf("parity: journal: parsing snapshot for disk %q: %w", diskID, err)
	}
	return snap, nil
}

func writeSnapshotAtomic(root, diskID string, snap journalSnapshot) error {
	data, err := json.Marshal(snap)
	if err != nil {
		return fmt.Errorf("parity: journal: encoding snapshot for disk %q: %w", diskID, err)
	}
	return atomicWriteFile(snapshotPath(root, diskID), data, 0o644)
}

// atomicWriteFile writes data to path via a temp file in the same
// directory, synced and closed before an atomic rename — mirroring
// internal/config's Generator.atomicWrite (#25) so a reader never
// observes a partially written snapshot and a crash mid-write leaves the
// previous snapshot (or none) rather than a truncated one. Duplicated
// here rather than imported: internal/config is a config-file concern
// with its own managed-file header and drift semantics (doc 01 §2) that
// don't apply to this package's own small persisted state, and this
// issue's declared scope is internal/parity/ only.
func atomicWriteFile(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("parity: journal: creating directory %s: %w", dir, err)
	}

	tmp, err := os.CreateTemp(dir, "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return fmt.Errorf("parity: journal: creating temp file in %s: %w", dir, err)
	}
	tmpPath := tmp.Name()
	defer func() { _ = os.Remove(tmpPath) }() // no-op once the rename below succeeds

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("parity: journal: writing %s: %w", tmpPath, err)
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("parity: journal: syncing %s: %w", tmpPath, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("parity: journal: closing %s: %w", tmpPath, err)
	}
	if err := os.Chmod(tmpPath, perm); err != nil {
		return fmt.Errorf("parity: journal: setting permissions on %s: %w", tmpPath, err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("parity: journal: renaming %s to %s: %w", tmpPath, path, err)
	}
	return nil
}
