package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestLoadOrGenerateTLSCertificateGeneratesAndReuses(t *testing.T) {
	dir := t.TempDir()
	certPath := filepath.Join(dir, "hoserva.crt")
	keyPath := filepath.Join(dir, "hoserva.key")

	cert1, err := loadOrGenerateTLSCertificate(certPath, keyPath)
	if err != nil {
		t.Fatalf("first load: %v", err)
	}
	info, err := os.Stat(keyPath)
	if err != nil {
		t.Fatalf("stat key: %v", err)
	}
	if perm := info.Mode().Perm(); perm != 0o600 {
		t.Errorf("key file mode = %o, want 0600", perm)
	}

	cert2, err := loadOrGenerateTLSCertificate(certPath, keyPath)
	if err != nil {
		t.Fatalf("second load: %v", err)
	}
	if string(cert1.Certificate[0]) != string(cert2.Certificate[0]) {
		t.Error("a second call should reuse the certificate generated by the first, not regenerate it")
	}
}

func TestLoadOrGenerateTLSCertificateRefusesReadableExistingKey(t *testing.T) {
	dir := t.TempDir()
	certPath := filepath.Join(dir, "hoserva.crt")
	keyPath := filepath.Join(dir, "hoserva.key")

	if _, err := loadOrGenerateTLSCertificate(certPath, keyPath); err != nil {
		t.Fatalf("first load: %v", err)
	}
	if err := os.Chmod(keyPath, 0o644); err != nil {
		t.Fatalf("chmod: %v", err)
	}

	if _, err := loadOrGenerateTLSCertificate(certPath, keyPath); err == nil {
		t.Fatal("expected an error for a group/world-readable existing TLS key file")
	}
}

func TestGenerateSelfSignedCertificateParses(t *testing.T) {
	certPEM, keyPEM, err := generateSelfSignedCertificate()
	if err != nil {
		t.Fatalf("generateSelfSignedCertificate: %v", err)
	}
	if len(certPEM) == 0 || len(keyPEM) == 0 {
		t.Fatal("expected non-empty cert and key PEM")
	}
}
