package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"math/big"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestLoadOrGenerateTLSCertificateGeneratesAndReuses(t *testing.T) {
	dir := t.TempDir()
	certPath := filepath.Join(dir, "hoserva.crt")
	keyPath := filepath.Join(dir, "hoserva.key")

	cert1, err := loadOrGenerateTLSCertificate(certPath, keyPath)
	if err != nil {
		t.Fatalf("first load: %v", err)
	}
	info, err := os.Stat(keyPath)
	if err != nil {
		t.Fatalf("stat key: %v", err)
	}
	if perm := info.Mode().Perm(); perm != 0o600 {
		t.Errorf("key file mode = %o, want 0600", perm)
	}

	cert2, err := loadOrGenerateTLSCertificate(certPath, keyPath)
	if err != nil {
		t.Fatalf("second load: %v", err)
	}
	if string(cert1.Certificate[0]) != string(cert2.Certificate[0]) {
		t.Error("a second call should reuse the certificate generated by the first, not regenerate it")
	}
}

func TestLoadOrGenerateTLSCertificateRefusesReadableExistingKey(t *testing.T) {
	dir := t.TempDir()
	certPath := filepath.Join(dir, "hoserva.crt")
	keyPath := filepath.Join(dir, "hoserva.key")

	if _, err := loadOrGenerateTLSCertificate(certPath, keyPath); err != nil {
		t.Fatalf("first load: %v", err)
	}
	if err := os.Chmod(keyPath, 0o644); err != nil {
		t.Fatalf("chmod: %v", err)
	}

	if _, err := loadOrGenerateTLSCertificate(certPath, keyPath); err == nil {
		t.Fatal("expected an error for a group/world-readable existing TLS key file")
	}
}

func TestWriteTLSCertificatePairLeavesValidPEMWithoutTempFiles(t *testing.T) {
	dir := t.TempDir()
	certPath := filepath.Join(dir, "hoserva.crt")
	keyPath := filepath.Join(dir, "hoserva.key")

	certPEM, keyPEM, err := generateSelfSignedCertificate()
	if err != nil {
		t.Fatalf("generateSelfSignedCertificate: %v", err)
	}
	if _, err := writeTLSCertificatePair(certPath, keyPath, certPEM, keyPEM); err != nil {
		t.Fatalf("writeTLSCertificatePair: %v", err)
	}
	if _, err := tls.LoadX509KeyPair(certPath, keyPath); err != nil {
		t.Fatalf("final paths should contain valid PEM: %v", err)
	}
	certInfo, err := os.Stat(certPath)
	if err != nil {
		t.Fatalf("stat cert: %v", err)
	}
	if perm := certInfo.Mode().Perm(); perm != 0o644 {
		t.Errorf("cert file mode = %o, want 0644", perm)
	}
	keyInfo, err := os.Stat(keyPath)
	if err != nil {
		t.Fatalf("stat key: %v", err)
	}
	if perm := keyInfo.Mode().Perm(); perm != 0o600 {
		t.Errorf("key file mode = %o, want 0600", perm)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("readdir: %v", err)
	}
	for _, entry := range entries {
		if strings.Contains(entry.Name(), ".tmp-") {
			t.Errorf("temp file left behind: %s", entry.Name())
		}
	}
}

func TestGenerateSelfSignedCertificateParses(t *testing.T) {
	certPEM, keyPEM, err := generateSelfSignedCertificate()
	if err != nil {
		t.Fatalf("generateSelfSignedCertificate: %v", err)
	}
	if len(certPEM) == 0 || len(keyPEM) == 0 {
		t.Fatal("expected non-empty cert and key PEM")
	}
}

func TestInstallTLSCertificateRejectsInvalidPEMAndLeavesExisting(t *testing.T) {
	dir := t.TempDir()
	certPath := filepath.Join(dir, "hoserva.crt")
	keyPath := filepath.Join(dir, "hoserva.key")
	if _, err := loadOrGenerateTLSCertificate(certPath, keyPath); err != nil {
		t.Fatal(err)
	}
	origCert, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatal(err)
	}
	if err := installTLSCertificate(certPath, keyPath, []byte("not-a-cert"), []byte("not-a-key")); err == nil {
		t.Fatal("expected invalid PEM to be rejected")
	}
	got, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(origCert) {
		t.Fatal("failed install must leave the existing certificate in place")
	}
}

func TestInstallTLSCertificateReplacesSelfSigned(t *testing.T) {
	dir := t.TempDir()
	certPath := filepath.Join(dir, "hoserva.crt")
	keyPath := filepath.Join(dir, "hoserva.key")
	if _, err := loadOrGenerateTLSCertificate(certPath, keyPath); err != nil {
		t.Fatal(err)
	}
	orig, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatal(err)
	}
	issuedCert, issuedKey, err := generateNamedCertificate("nas.example.com")
	if err != nil {
		t.Fatal(err)
	}
	if err := installTLSCertificate(certPath, keyPath, issuedCert, issuedKey); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) == string(orig) {
		t.Fatal("install should replace the self-signed certificate")
	}
	info, err := os.Stat(keyPath)
	if err != nil {
		t.Fatal(err)
	}
	if perm := info.Mode().Perm(); perm != 0o600 {
		t.Errorf("key file mode = %o, want 0600", perm)
	}
	pair, err := tls.LoadX509KeyPair(certPath, keyPath)
	if err != nil {
		t.Fatal(err)
	}
	parsed, err := x509.ParseCertificate(pair.Certificate[0])
	if err != nil {
		t.Fatal(err)
	}
	view := tlsCertViewFromParsed(parsed)
	if view.Kind != "lets_encrypt" || view.Domain != "nas.example.com" {
		t.Fatalf("view = %+v", view)
	}
}

func TestInstallTLSCertificate_StagingFailureLeavesExistingPairUntouched(t *testing.T) {
	dir := t.TempDir()
	certPath := filepath.Join(dir, "hoserva.crt")
	keyPath := filepath.Join(dir, "hoserva.key")
	if _, err := loadOrGenerateTLSCertificate(certPath, keyPath); err != nil {
		t.Fatal(err)
	}
	certBefore, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatal(err)
	}
	keyBefore, err := os.ReadFile(keyPath)
	if err != nil {
		t.Fatal(err)
	}
	certInfo, err := os.Stat(certPath)
	if err != nil {
		t.Fatal(err)
	}
	keyInfo, err := os.Stat(keyPath)
	if err != nil {
		t.Fatal(err)
	}

	issuedCert, issuedKey, err := generateNamedCertificate("nas.example.com")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(dir, 0o555); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(dir, 0o755) })
	if err := installTLSCertificate(certPath, keyPath, issuedCert, issuedKey); err == nil {
		t.Fatal("expected install to fail when the certificate directory is not writable")
	}
	if err := os.Chmod(dir, 0o755); err != nil {
		t.Fatal(err)
	}

	certAfter, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatal(err)
	}
	keyAfter, err := os.ReadFile(keyPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(certAfter) != string(certBefore) || string(keyAfter) != string(keyBefore) {
		t.Fatal("staging failure rewrote the existing certificate pair")
	}
	certInfoAfter, err := os.Stat(certPath)
	if err != nil {
		t.Fatal(err)
	}
	keyInfoAfter, err := os.Stat(keyPath)
	if err != nil {
		t.Fatal(err)
	}
	if !certInfo.ModTime().Equal(certInfoAfter.ModTime()) || !keyInfo.ModTime().Equal(keyInfoAfter.ModTime()) {
		t.Fatal("staging failure truncated or rewrote the existing certificate files")
	}
}

func TestLoadOrGenerateTLSCertificate_RecoversInterruptedPairFromBackup(t *testing.T) {
	dir := t.TempDir()
	certPath := filepath.Join(dir, "hoserva.crt")
	keyPath := filepath.Join(dir, "hoserva.key")
	original, err := loadOrGenerateTLSCertificate(certPath, keyPath)
	if err != nil {
		t.Fatal(err)
	}
	issuedCert, issuedKey, err := generateNamedCertificate("nas.example.com")
	if err != nil {
		t.Fatal(err)
	}
	if err := installTLSCertificate(certPath, keyPath, issuedCert, issuedKey); err != nil {
		t.Fatal(err)
	}

	// The live certificate no longer matches its key. The snapshot taken
	// before that install is the previous pair.
	if err := os.WriteFile(certPath, issuedCert[:len(issuedCert)/2], 0o644); err != nil {
		t.Fatal(err)
	}
	recovered, err := loadOrGenerateTLSCertificate(certPath, keyPath)
	if err != nil {
		t.Fatalf("load after interrupted install: %v", err)
	}
	if string(recovered.Certificate[0]) != string(original.Certificate[0]) {
		t.Fatal("interrupted install should restore the snapshotted pair, not keep a mismatched one or mint a new certificate")
	}
}

func generateNamedCertificate(domain string) (certPEM, keyPEM []byte, err error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, err
	}
	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, nil, err
	}
	now := time.Now()
	template := &x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{CommonName: domain},
		NotBefore:    now.Add(-time.Hour),
		NotAfter:     now.Add(90 * 24 * time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		DNSNames:     []string{domain},
	}
	der, err := x509.CreateCertificate(rand.Reader, template, template, &key.PublicKey, key)
	if err != nil {
		return nil, nil, err
	}
	certPEM = pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	keyDER, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		return nil, nil, err
	}
	keyPEM = pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER})
	return certPEM, keyPEM, nil
}
