-- Generated by `make db-migration` on 2026-09-16.
-- Do not edit this file — it is immutable once created (D16). A mistake
-- is corrected by changing schema.sql and generating another migration.
CREATE TABLE schema_info (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    installation_id TEXT NOT NULL,
    created_at TEXT NOT NULL
);
