-- Generated by `make db-migration` on 2026-09-16.
-- Do not edit this file — it is immutable once created (D16). A mistake
-- is corrected by changing schema.sql and generating another migration.
ALTER TABLE `users` ADD COLUMN `totp_pending_secret` blob;
CREATE TABLE machine_key_check (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    check_value BLOB NOT NULL,
    created_at TEXT NOT NULL
);
