// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: acme.sql

package storedb

import (
	"context"
	"database/sql"
)

const deleteACMEConfig = `-- name: DeleteACMEConfig :exec
DELETE FROM acme_config WHERE id = 1
`

func (q *Queries) DeleteACMEConfig(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteACMEConfig)
	return err
}

const getACMEConfig = `-- name: GetACMEConfig :one

SELECT id, domain, provider, provider_config, dns_secret, account_key, enabled, last_error, updated_at
FROM acme_config WHERE id = 1
`

// sqlc input (#211, Q60): typed Go query code for the acme_config table,
// generated into internal/store/db/ by `make gen`. Deliberately no
// comment other than each "-- name:" line between queries below (see
// jobs.sql for the same note about sqlc's SQLite engine mis-slicing raw
// source around extra comment lines).
func (q *Queries) GetACMEConfig(ctx context.Context) (*AcmeConfig, error) {
	row := q.db.QueryRowContext(ctx, getACMEConfig)
	var i AcmeConfig
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Provider,
		&i.ProviderConfig,
		&i.DnsSecret,
		&i.AccountKey,
		&i.Enabled,
		&i.LastError,
		&i.UpdatedAt,
	)
	return &i, err
}

const hasEncryptedACMESecrets = `-- name: HasEncryptedACMESecrets :one
SELECT EXISTS(
    SELECT 1 FROM acme_config
    WHERE length(dns_secret) > 0 OR length(account_key) > 0
)
`

func (q *Queries) HasEncryptedACMESecrets(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasEncryptedACMESecrets)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listACMESecrets = `-- name: ListACMESecrets :many
SELECT 'dns_secret' AS col, dns_secret AS ciphertext FROM acme_config WHERE id = 1 AND length(dns_secret) > 0
UNION ALL
SELECT 'account_key' AS col, account_key AS ciphertext FROM acme_config WHERE id = 1 AND length(account_key) > 0
`

type ListACMESecretsRow struct {
	Col        string `json:"col"`
	Ciphertext []byte `json:"ciphertext"`
}

func (q *Queries) ListACMESecrets(ctx context.Context) ([]*ListACMESecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, listACMESecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListACMESecretsRow
	for rows.Next() {
		var i ListACMESecretsRow
		if err := rows.Scan(&i.Col, &i.Ciphertext); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setACMEAccountKey = `-- name: SetACMEAccountKey :exec
UPDATE acme_config SET account_key = ?, updated_at = ? WHERE id = 1
`

type SetACMEAccountKeyParams struct {
	AccountKey []byte `json:"account_key"`
	UpdatedAt  string `json:"updated_at"`
}

func (q *Queries) SetACMEAccountKey(ctx context.Context, arg SetACMEAccountKeyParams) error {
	_, err := q.db.ExecContext(ctx, setACMEAccountKey, arg.AccountKey, arg.UpdatedAt)
	return err
}

const setACMEEnabled = `-- name: SetACMEEnabled :execrows
UPDATE acme_config SET enabled = ?, last_error = ?, updated_at = ? WHERE id = 1
`

type SetACMEEnabledParams struct {
	Enabled   int64          `json:"enabled"`
	LastError sql.NullString `json:"last_error"`
	UpdatedAt string         `json:"updated_at"`
}

func (q *Queries) SetACMEEnabled(ctx context.Context, arg SetACMEEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setACMEEnabled, arg.Enabled, arg.LastError, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setACMELastError = `-- name: SetACMELastError :exec
UPDATE acme_config SET last_error = ?, updated_at = ? WHERE id = 1
`

type SetACMELastErrorParams struct {
	LastError sql.NullString `json:"last_error"`
	UpdatedAt string         `json:"updated_at"`
}

func (q *Queries) SetACMELastError(ctx context.Context, arg SetACMELastErrorParams) error {
	_, err := q.db.ExecContext(ctx, setACMELastError, arg.LastError, arg.UpdatedAt)
	return err
}

const upsertACMEConfig = `-- name: UpsertACMEConfig :exec
INSERT INTO acme_config (
    id, domain, provider, provider_config, dns_secret, account_key, enabled, last_error, updated_at
) VALUES (
    1, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (id) DO UPDATE SET
    domain = excluded.domain,
    provider = excluded.provider,
    provider_config = excluded.provider_config,
    dns_secret = excluded.dns_secret,
    account_key = excluded.account_key,
    enabled = excluded.enabled,
    last_error = excluded.last_error,
    updated_at = excluded.updated_at
`

type UpsertACMEConfigParams struct {
	Domain         string         `json:"domain"`
	Provider       string         `json:"provider"`
	ProviderConfig string         `json:"provider_config"`
	DnsSecret      []byte         `json:"dns_secret"`
	AccountKey     []byte         `json:"account_key"`
	Enabled        int64          `json:"enabled"`
	LastError      sql.NullString `json:"last_error"`
	UpdatedAt      string         `json:"updated_at"`
}

func (q *Queries) UpsertACMEConfig(ctx context.Context, arg UpsertACMEConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertACMEConfig,
		arg.Domain,
		arg.Provider,
		arg.ProviderConfig,
		arg.DnsSecret,
		arg.AccountKey,
		arg.Enabled,
		arg.LastError,
		arg.UpdatedAt,
	)
	return err
}
