// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package storedb

import (
	"context"
)

const createApiToken = `-- name: CreateApiToken :exec

INSERT INTO api_tokens (token_hash, user_id, name, role, created_at) VALUES (?, ?, ?, ?, ?)
`

type CreateApiTokenParams struct {
	TokenHash string `json:"token_hash"`
	UserID    string `json:"user_id"`
	Name      string `json:"name"`
	Role      string `json:"role"`
	CreatedAt string `json:"created_at"`
}

// sqlc input (#50, Q43, Q60): typed Go query code for the api_tokens
// table, generated into internal/store/db/ by `make gen`.
func (q *Queries) CreateApiToken(ctx context.Context, arg CreateApiTokenParams) error {
	_, err := q.db.ExecContext(ctx, createApiToken,
		arg.TokenHash,
		arg.UserID,
		arg.Name,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const deleteApiToken = `-- name: DeleteApiToken :execrows
DELETE FROM api_tokens WHERE token_hash = ?
`

func (q *Queries) DeleteApiToken(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteApiToken, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUserApiTokens = `-- name: DeleteUserApiTokens :exec
DELETE FROM api_tokens WHERE user_id = ?
`

func (q *Queries) DeleteUserApiTokens(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserApiTokens, userID)
	return err
}

const getApiTokenByHash = `-- name: GetApiTokenByHash :one
SELECT token_hash, user_id, name, role, created_at FROM api_tokens WHERE token_hash = ?
`

func (q *Queries) GetApiTokenByHash(ctx context.Context, tokenHash string) (*ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getApiTokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return &i, err
}
