// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appdata_backup.sql

package storedb

import (
	"context"
)

const listAppdataBackupContainers = `-- name: ListAppdataBackupContainers :many

SELECT container, stop, included, updated_at
FROM appdata_backup_containers
ORDER BY container ASC
`

// sqlc input (#61): the per-container appdata backup policy, generated
// into internal/store/db/ by `make gen`.
func (q *Queries) ListAppdataBackupContainers(ctx context.Context) ([]*AppdataBackupContainer, error) {
	rows, err := q.db.QueryContext(ctx, listAppdataBackupContainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AppdataBackupContainer
	for rows.Next() {
		var i AppdataBackupContainer
		if err := rows.Scan(
			&i.Container,
			&i.Stop,
			&i.Included,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAppdataBackupContainer = `-- name: UpsertAppdataBackupContainer :exec
INSERT INTO appdata_backup_containers (container, stop, included, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (container) DO UPDATE SET
    stop = excluded.stop,
    included = excluded.included,
    updated_at = excluded.updated_at
`

type UpsertAppdataBackupContainerParams struct {
	Container string `json:"container"`
	Stop      int64  `json:"stop"`
	Included  int64  `json:"included"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) UpsertAppdataBackupContainer(ctx context.Context, arg UpsertAppdataBackupContainerParams) error {
	_, err := q.db.ExecContext(ctx, upsertAppdataBackupContainer,
		arg.Container,
		arg.Stop,
		arg.Included,
		arg.UpdatedAt,
	)
	return err
}
