// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: array_maintenance.sql

package storedb

import (
	"context"
)

const getArrayMaintenance = `-- name: GetArrayMaintenance :one

SELECT id, maintenance, array_stopped, updated_at
FROM array_maintenance
WHERE id = 1
`

// sqlc input (#387): typed Go query code for array_maintenance, generated
// into internal/store/db/ by `make gen`.
func (q *Queries) GetArrayMaintenance(ctx context.Context) (*ArrayMaintenance, error) {
	row := q.db.QueryRowContext(ctx, getArrayMaintenance)
	var i ArrayMaintenance
	err := row.Scan(
		&i.ID,
		&i.Maintenance,
		&i.ArrayStopped,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertArrayMaintenance = `-- name: UpsertArrayMaintenance :exec
INSERT INTO array_maintenance (id, maintenance, array_stopped, updated_at)
VALUES (1, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    maintenance = excluded.maintenance,
    array_stopped = excluded.array_stopped,
    updated_at = excluded.updated_at
`

type UpsertArrayMaintenanceParams struct {
	Maintenance  int64  `json:"maintenance"`
	ArrayStopped int64  `json:"array_stopped"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) UpsertArrayMaintenance(ctx context.Context, arg UpsertArrayMaintenanceParams) error {
	_, err := q.db.ExecContext(ctx, upsertArrayMaintenance, arg.Maintenance, arg.ArrayStopped, arg.UpdatedAt)
	return err
}
