// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: array.sql

package storedb

import (
	"context"
	"database/sql"
)

const countArraySettings = `-- name: CountArraySettings :one
SELECT COUNT(*) FROM array_settings
`

func (q *Queries) CountArraySettings(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArraySettings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getArrayDataDiskByMountpoint = `-- name: GetArrayDataDiskByMountpoint :one
SELECT
    id, role, role_index, device, filesystem, fs_uuid,
    wwn, serial, by_id_name, weak_identity, mountpoint
FROM array_disks WHERE mountpoint = ? AND role = 'data'
`

func (q *Queries) GetArrayDataDiskByMountpoint(ctx context.Context, mountpoint string) (*ArrayDisk, error) {
	row := q.db.QueryRowContext(ctx, getArrayDataDiskByMountpoint, mountpoint)
	var i ArrayDisk
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.RoleIndex,
		&i.Device,
		&i.Filesystem,
		&i.FsUuid,
		&i.Wwn,
		&i.Serial,
		&i.ByIDName,
		&i.WeakIdentity,
		&i.Mountpoint,
	)
	return &i, err
}

const getArraySettings = `-- name: GetArraySettings :one
SELECT id, create_policy, min_free_space, created_at
FROM array_settings WHERE id = 1
`

func (q *Queries) GetArraySettings(ctx context.Context) (*ArraySetting, error) {
	row := q.db.QueryRowContext(ctx, getArraySettings)
	var i ArraySetting
	err := row.Scan(
		&i.ID,
		&i.CreatePolicy,
		&i.MinFreeSpace,
		&i.CreatedAt,
	)
	return &i, err
}

const insertArrayDisk = `-- name: InsertArrayDisk :exec
INSERT INTO array_disks (
    role, role_index, device, filesystem, fs_uuid,
    wwn, serial, by_id_name, weak_identity, mountpoint
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?
)
`

type InsertArrayDiskParams struct {
	Role         string         `json:"role"`
	RoleIndex    int64          `json:"role_index"`
	Device       string         `json:"device"`
	Filesystem   string         `json:"filesystem"`
	FsUuid       string         `json:"fs_uuid"`
	Wwn          sql.NullString `json:"wwn"`
	Serial       sql.NullString `json:"serial"`
	ByIDName     sql.NullString `json:"by_id_name"`
	WeakIdentity int64          `json:"weak_identity"`
	Mountpoint   string         `json:"mountpoint"`
}

func (q *Queries) InsertArrayDisk(ctx context.Context, arg InsertArrayDiskParams) error {
	_, err := q.db.ExecContext(ctx, insertArrayDisk,
		arg.Role,
		arg.RoleIndex,
		arg.Device,
		arg.Filesystem,
		arg.FsUuid,
		arg.Wwn,
		arg.Serial,
		arg.ByIDName,
		arg.WeakIdentity,
		arg.Mountpoint,
	)
	return err
}

const insertArraySettings = `-- name: InsertArraySettings :exec

INSERT INTO array_settings (id, create_policy, min_free_space, created_at)
VALUES (1, ?, ?, ?)
`

type InsertArraySettingsParams struct {
	CreatePolicy string `json:"create_policy"`
	MinFreeSpace string `json:"min_free_space"`
	CreatedAt    string `json:"created_at"`
}

// sqlc input (#180, Q60): typed Go query code for the array_settings and
// array_disks tables, generated into internal/store/db/ by `make gen`.
// Deliberately no comment other than each "-- name:" line between queries
// below (see jobs.sql for the same note about sqlc's SQLite engine
// mis-slicing raw source around extra comment lines). Doc comments live
// on the hand-written Go wrapper in internal/store/array.go instead.
func (q *Queries) InsertArraySettings(ctx context.Context, arg InsertArraySettingsParams) error {
	_, err := q.db.ExecContext(ctx, insertArraySettings, arg.CreatePolicy, arg.MinFreeSpace, arg.CreatedAt)
	return err
}

const listArrayDisks = `-- name: ListArrayDisks :many
SELECT
    id, role, role_index, device, filesystem, fs_uuid,
    wwn, serial, by_id_name, weak_identity, mountpoint
FROM array_disks
ORDER BY
    CASE role
        WHEN 'parity' THEN 1
        WHEN 'data' THEN 2
        WHEN 'cache' THEN 3
        ELSE 4
    END,
    role_index ASC
`

func (q *Queries) ListArrayDisks(ctx context.Context) ([]*ArrayDisk, error) {
	rows, err := q.db.QueryContext(ctx, listArrayDisks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ArrayDisk
	for rows.Next() {
		var i ArrayDisk
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.RoleIndex,
			&i.Device,
			&i.Filesystem,
			&i.FsUuid,
			&i.Wwn,
			&i.Serial,
			&i.ByIDName,
			&i.WeakIdentity,
			&i.Mountpoint,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceArrayDataDiskIdentity = `-- name: ReplaceArrayDataDiskIdentity :execrows
UPDATE array_disks
SET device = ?, filesystem = ?, fs_uuid = ?,
    wwn = ?, serial = ?, by_id_name = ?, weak_identity = ?
WHERE mountpoint = ? AND role = 'data'
`

type ReplaceArrayDataDiskIdentityParams struct {
	Device       string         `json:"device"`
	Filesystem   string         `json:"filesystem"`
	FsUuid       string         `json:"fs_uuid"`
	Wwn          sql.NullString `json:"wwn"`
	Serial       sql.NullString `json:"serial"`
	ByIDName     sql.NullString `json:"by_id_name"`
	WeakIdentity int64          `json:"weak_identity"`
	Mountpoint   string         `json:"mountpoint"`
}

func (q *Queries) ReplaceArrayDataDiskIdentity(ctx context.Context, arg ReplaceArrayDataDiskIdentityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, replaceArrayDataDiskIdentity,
		arg.Device,
		arg.Filesystem,
		arg.FsUuid,
		arg.Wwn,
		arg.Serial,
		arg.ByIDName,
		arg.WeakIdentity,
		arg.Mountpoint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
