// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: array.sql

package storedb

import (
	"context"
	"database/sql"
)

const advanceArrayDiskRemovalState = `-- name: AdvanceArrayDiskRemovalState :execrows
UPDATE array_disks SET removal_state = ?1, removal_job_id = ?2
WHERE mountpoint = ?3 AND role = 'data'
    AND removal_state IN (?4, ?5)
`

type AdvanceArrayDiskRemovalStateParams struct {
	ToState    sql.NullString `json:"to_state"`
	JobID      sql.NullString `json:"job_id"`
	Mountpoint string         `json:"mountpoint"`
	FromState  sql.NullString `json:"from_state"`
	SameState  sql.NullString `json:"same_state"`
}

func (q *Queries) AdvanceArrayDiskRemovalState(ctx context.Context, arg AdvanceArrayDiskRemovalStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceArrayDiskRemovalState,
		arg.ToState,
		arg.JobID,
		arg.Mountpoint,
		arg.FromState,
		arg.SameState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelArrayDiskRemovalState = `-- name: CancelArrayDiskRemovalState :execrows
UPDATE array_disks SET removal_state = NULL, removal_job_id = NULL
WHERE mountpoint = ?1 AND role = 'data'
    AND removal_state IN ('evacuating', 'evacuated')
    AND removal_state = ?2
    AND removal_job_id IS ?3
`

type CancelArrayDiskRemovalStateParams struct {
	Mountpoint    string         `json:"mountpoint"`
	ExpectedState sql.NullString `json:"expected_state"`
	ExpectedJobID sql.NullString `json:"expected_job_id"`
}

func (q *Queries) CancelArrayDiskRemovalState(ctx context.Context, arg CancelArrayDiskRemovalStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelArrayDiskRemovalState, arg.Mountpoint, arg.ExpectedState, arg.ExpectedJobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countArraySettings = `-- name: CountArraySettings :one
SELECT COUNT(*) FROM array_settings
`

func (q *Queries) CountArraySettings(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArraySettings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUnlistedArrayDataDisk = `-- name: DeleteUnlistedArrayDataDisk :execrows
DELETE FROM array_disks WHERE mountpoint = ? AND role = 'data' AND removal_state = 'unlisted'
`

func (q *Queries) DeleteUnlistedArrayDataDisk(ctx context.Context, mountpoint string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnlistedArrayDataDisk, mountpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getArrayDataDiskByMountpoint = `-- name: GetArrayDataDiskByMountpoint :one
SELECT
    id, role, role_index, device, filesystem, fs_uuid, size_bytes,
    wwn, serial, by_id_name, weak_identity, mountpoint, removal_state, removal_job_id
FROM array_disks WHERE mountpoint = ? AND role = 'data'
`

func (q *Queries) GetArrayDataDiskByMountpoint(ctx context.Context, mountpoint string) (*ArrayDisk, error) {
	row := q.db.QueryRowContext(ctx, getArrayDataDiskByMountpoint, mountpoint)
	var i ArrayDisk
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.RoleIndex,
		&i.Device,
		&i.Filesystem,
		&i.FsUuid,
		&i.SizeBytes,
		&i.Wwn,
		&i.Serial,
		&i.ByIDName,
		&i.WeakIdentity,
		&i.Mountpoint,
		&i.RemovalState,
		&i.RemovalJobID,
	)
	return &i, err
}

const getArraySettings = `-- name: GetArraySettings :one
SELECT id, create_policy, min_free_space, created_at
FROM array_settings WHERE id = 1
`

func (q *Queries) GetArraySettings(ctx context.Context) (*ArraySetting, error) {
	row := q.db.QueryRowContext(ctx, getArraySettings)
	var i ArraySetting
	err := row.Scan(
		&i.ID,
		&i.CreatePolicy,
		&i.MinFreeSpace,
		&i.CreatedAt,
	)
	return &i, err
}

const getRemovingArrayDisk = `-- name: GetRemovingArrayDisk :one
SELECT mountpoint, removal_state FROM array_disks WHERE removal_state IS NOT NULL LIMIT 1
`

type GetRemovingArrayDiskRow struct {
	Mountpoint   string         `json:"mountpoint"`
	RemovalState sql.NullString `json:"removal_state"`
}

func (q *Queries) GetRemovingArrayDisk(ctx context.Context) (*GetRemovingArrayDiskRow, error) {
	row := q.db.QueryRowContext(ctx, getRemovingArrayDisk)
	var i GetRemovingArrayDiskRow
	err := row.Scan(&i.Mountpoint, &i.RemovalState)
	return &i, err
}

const insertArrayDisk = `-- name: InsertArrayDisk :exec
INSERT INTO array_disks (
    role, role_index, device, filesystem, fs_uuid, size_bytes,
    wwn, serial, by_id_name, weak_identity, mountpoint
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?
)
`

type InsertArrayDiskParams struct {
	Role         string         `json:"role"`
	RoleIndex    int64          `json:"role_index"`
	Device       string         `json:"device"`
	Filesystem   string         `json:"filesystem"`
	FsUuid       string         `json:"fs_uuid"`
	SizeBytes    sql.NullInt64  `json:"size_bytes"`
	Wwn          sql.NullString `json:"wwn"`
	Serial       sql.NullString `json:"serial"`
	ByIDName     sql.NullString `json:"by_id_name"`
	WeakIdentity int64          `json:"weak_identity"`
	Mountpoint   string         `json:"mountpoint"`
}

func (q *Queries) InsertArrayDisk(ctx context.Context, arg InsertArrayDiskParams) error {
	_, err := q.db.ExecContext(ctx, insertArrayDisk,
		arg.Role,
		arg.RoleIndex,
		arg.Device,
		arg.Filesystem,
		arg.FsUuid,
		arg.SizeBytes,
		arg.Wwn,
		arg.Serial,
		arg.ByIDName,
		arg.WeakIdentity,
		arg.Mountpoint,
	)
	return err
}

const insertArraySettings = `-- name: InsertArraySettings :exec

INSERT INTO array_settings (id, create_policy, min_free_space, created_at)
VALUES (1, ?, ?, ?)
`

type InsertArraySettingsParams struct {
	CreatePolicy string `json:"create_policy"`
	MinFreeSpace string `json:"min_free_space"`
	CreatedAt    string `json:"created_at"`
}

// sqlc input (#180, Q60): typed Go query code for the array_settings and
// array_disks tables, generated into internal/store/db/ by `make gen`.
// Deliberately no comment other than each "-- name:" line between queries
// below (see jobs.sql for the same note about sqlc's SQLite engine
// mis-slicing raw source around extra comment lines). Doc comments live
// on the hand-written Go wrapper in internal/store/array.go instead.
func (q *Queries) InsertArraySettings(ctx context.Context, arg InsertArraySettingsParams) error {
	_, err := q.db.ExecContext(ctx, insertArraySettings, arg.CreatePolicy, arg.MinFreeSpace, arg.CreatedAt)
	return err
}

const listArrayDisks = `-- name: ListArrayDisks :many
SELECT
    id, role, role_index, device, filesystem, fs_uuid, size_bytes,
    wwn, serial, by_id_name, weak_identity, mountpoint, removal_state, removal_job_id
FROM array_disks
ORDER BY
    CASE role
        WHEN 'parity' THEN 1
        WHEN 'data' THEN 2
        WHEN 'cache' THEN 3
        ELSE 4
    END,
    role_index ASC
`

func (q *Queries) ListArrayDisks(ctx context.Context) ([]*ArrayDisk, error) {
	rows, err := q.db.QueryContext(ctx, listArrayDisks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ArrayDisk
	for rows.Next() {
		var i ArrayDisk
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.RoleIndex,
			&i.Device,
			&i.Filesystem,
			&i.FsUuid,
			&i.SizeBytes,
			&i.Wwn,
			&i.Serial,
			&i.ByIDName,
			&i.WeakIdentity,
			&i.Mountpoint,
			&i.RemovalState,
			&i.RemovalJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseArrayDiskRemovalState = `-- name: ReleaseArrayDiskRemovalState :execrows
UPDATE array_disks SET removal_state = NULL, removal_job_id = NULL
WHERE mountpoint = ? AND role = 'data' AND removal_state = 'evacuating' AND removal_job_id = ?
`

type ReleaseArrayDiskRemovalStateParams struct {
	Mountpoint   string         `json:"mountpoint"`
	RemovalJobID sql.NullString `json:"removal_job_id"`
}

func (q *Queries) ReleaseArrayDiskRemovalState(ctx context.Context, arg ReleaseArrayDiskRemovalStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseArrayDiskRemovalState, arg.Mountpoint, arg.RemovalJobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const replaceArrayDataDiskIdentity = `-- name: ReplaceArrayDataDiskIdentity :execrows
UPDATE array_disks
SET device = ?, filesystem = ?, fs_uuid = ?, size_bytes = ?,
    wwn = ?, serial = ?, by_id_name = ?, weak_identity = ?
WHERE mountpoint = ? AND role = 'data'
`

type ReplaceArrayDataDiskIdentityParams struct {
	Device       string         `json:"device"`
	Filesystem   string         `json:"filesystem"`
	FsUuid       string         `json:"fs_uuid"`
	SizeBytes    sql.NullInt64  `json:"size_bytes"`
	Wwn          sql.NullString `json:"wwn"`
	Serial       sql.NullString `json:"serial"`
	ByIDName     sql.NullString `json:"by_id_name"`
	WeakIdentity int64          `json:"weak_identity"`
	Mountpoint   string         `json:"mountpoint"`
}

func (q *Queries) ReplaceArrayDataDiskIdentity(ctx context.Context, arg ReplaceArrayDataDiskIdentityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, replaceArrayDataDiskIdentity,
		arg.Device,
		arg.Filesystem,
		arg.FsUuid,
		arg.SizeBytes,
		arg.Wwn,
		arg.Serial,
		arg.ByIDName,
		arg.WeakIdentity,
		arg.Mountpoint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setArrayDiskRemovalState = `-- name: SetArrayDiskRemovalState :execrows
UPDATE array_disks SET removal_state = ?, removal_job_id = ? WHERE mountpoint = ? AND role = 'data'
`

type SetArrayDiskRemovalStateParams struct {
	RemovalState sql.NullString `json:"removal_state"`
	RemovalJobID sql.NullString `json:"removal_job_id"`
	Mountpoint   string         `json:"mountpoint"`
}

func (q *Queries) SetArrayDiskRemovalState(ctx context.Context, arg SetArrayDiskRemovalStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setArrayDiskRemovalState, arg.RemovalState, arg.RemovalJobID, arg.Mountpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upgradeArrayParityDiskSlot = `-- name: UpgradeArrayParityDiskSlot :execrows
UPDATE array_disks
SET device = ?, filesystem = ?, fs_uuid = ?, size_bytes = ?,
    wwn = ?, serial = ?, by_id_name = ?, weak_identity = ?,
    mountpoint = ?9
WHERE mountpoint = ?10 AND role = 'parity'
`

type UpgradeArrayParityDiskSlotParams struct {
	Device        string         `json:"device"`
	Filesystem    string         `json:"filesystem"`
	FsUuid        string         `json:"fs_uuid"`
	SizeBytes     sql.NullInt64  `json:"size_bytes"`
	Wwn           sql.NullString `json:"wwn"`
	Serial        sql.NullString `json:"serial"`
	ByIDName      sql.NullString `json:"by_id_name"`
	WeakIdentity  int64          `json:"weak_identity"`
	NewMountpoint string         `json:"new_mountpoint"`
	OldMountpoint string         `json:"old_mountpoint"`
}

func (q *Queries) UpgradeArrayParityDiskSlot(ctx context.Context, arg UpgradeArrayParityDiskSlotParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upgradeArrayParityDiskSlot,
		arg.Device,
		arg.Filesystem,
		arg.FsUuid,
		arg.SizeBytes,
		arg.Wwn,
		arg.Serial,
		arg.ByIDName,
		arg.WeakIdentity,
		arg.NewMountpoint,
		arg.OldMountpoint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
