// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package storedb

import (
	"context"
	"database/sql"
)

const countAuditLog = `-- name: CountAuditLog :one
SELECT COUNT(*) FROM audit_log
`

func (q *Queries) CountAuditLog(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLog)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLogEntry = `-- name: InsertAuditLogEntry :exec

INSERT INTO audit_log (actor, action, detail, at) VALUES (?, ?, ?, ?)
`

type InsertAuditLogEntryParams struct {
	Actor  string         `json:"actor"`
	Action string         `json:"action"`
	Detail sql.NullString `json:"detail"`
	At     string         `json:"at"`
}

// sqlc input (#110, Q60): typed Go query code for the audit_log table,
// generated into internal/store/db/ by `make gen`. Deliberately no
// comment other than each "-- name:" line between queries below (see
// jobs.sql for the same note about sqlc's SQLite engine).
func (q *Queries) InsertAuditLogEntry(ctx context.Context, arg InsertAuditLogEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLogEntry,
		arg.Actor,
		arg.Action,
		arg.Detail,
		arg.At,
	)
	return err
}

const pruneAuditLog = `-- name: PruneAuditLog :exec
DELETE FROM audit_log WHERE at < ?
`

func (q *Queries) PruneAuditLog(ctx context.Context, at string) error {
	_, err := q.db.ExecContext(ctx, pruneAuditLog, at)
	return err
}
