// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backup_destinations.sql

package storedb

import (
	"context"
	"database/sql"
)

const createBackupDestination = `-- name: CreateBackupDestination :exec
INSERT INTO backup_destinations (
    id, name, type, path, options, secrets, enabled, encrypt, retention_daily,
    retention_weekly, retention_monthly, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateBackupDestinationParams struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	Type             string `json:"type"`
	Path             string `json:"path"`
	Options          string `json:"options"`
	Secrets          []byte `json:"secrets"`
	Enabled          int64  `json:"enabled"`
	Encrypt          int64  `json:"encrypt"`
	RetentionDaily   int64  `json:"retention_daily"`
	RetentionWeekly  int64  `json:"retention_weekly"`
	RetentionMonthly int64  `json:"retention_monthly"`
	CreatedAt        string `json:"created_at"`
}

func (q *Queries) CreateBackupDestination(ctx context.Context, arg CreateBackupDestinationParams) error {
	_, err := q.db.ExecContext(ctx, createBackupDestination,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Path,
		arg.Options,
		arg.Secrets,
		arg.Enabled,
		arg.Encrypt,
		arg.RetentionDaily,
		arg.RetentionWeekly,
		arg.RetentionMonthly,
		arg.CreatedAt,
	)
	return err
}

const deleteBackupDestination = `-- name: DeleteBackupDestination :execrows
DELETE FROM backup_destinations WHERE id = ?
`

func (q *Queries) DeleteBackupDestination(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBackupDestination, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBackupDestination = `-- name: GetBackupDestination :one
SELECT id, name, type, path, options, secrets, enabled, encrypt, retention_daily,
       retention_weekly, retention_monthly, last_successful_backup_at,
       stale_alerted_at, created_at
FROM backup_destinations WHERE id = ?
`

func (q *Queries) GetBackupDestination(ctx context.Context, id string) (*BackupDestination, error) {
	row := q.db.QueryRowContext(ctx, getBackupDestination, id)
	var i BackupDestination
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Path,
		&i.Options,
		&i.Secrets,
		&i.Enabled,
		&i.Encrypt,
		&i.RetentionDaily,
		&i.RetentionWeekly,
		&i.RetentionMonthly,
		&i.LastSuccessfulBackupAt,
		&i.StaleAlertedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const listBackupDestinations = `-- name: ListBackupDestinations :many

SELECT id, name, type, path, options, secrets, enabled, encrypt, retention_daily,
       retention_weekly, retention_monthly, last_successful_backup_at,
       stale_alerted_at, created_at
FROM backup_destinations ORDER BY created_at, id
`

// sqlc input (#60, Q60): typed Go query code for the backup_destinations
// table, generated into internal/store/db/ by `make gen`.
func (q *Queries) ListBackupDestinations(ctx context.Context) ([]*BackupDestination, error) {
	rows, err := q.db.QueryContext(ctx, listBackupDestinations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*BackupDestination
	for rows.Next() {
		var i BackupDestination
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Path,
			&i.Options,
			&i.Secrets,
			&i.Enabled,
			&i.Encrypt,
			&i.RetentionDaily,
			&i.RetentionWeekly,
			&i.RetentionMonthly,
			&i.LastSuccessfulBackupAt,
			&i.StaleAlertedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBackupDestinationStaleAlerted = `-- name: MarkBackupDestinationStaleAlerted :execrows
UPDATE backup_destinations SET stale_alerted_at = ? WHERE id = ?
`

type MarkBackupDestinationStaleAlertedParams struct {
	StaleAlertedAt sql.NullString `json:"stale_alerted_at"`
	ID             string         `json:"id"`
}

func (q *Queries) MarkBackupDestinationStaleAlerted(ctx context.Context, arg MarkBackupDestinationStaleAlertedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markBackupDestinationStaleAlerted, arg.StaleAlertedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordBackupDestinationSuccess = `-- name: RecordBackupDestinationSuccess :execrows
UPDATE backup_destinations
SET last_successful_backup_at = ?, stale_alerted_at = NULL
WHERE id = ?
`

type RecordBackupDestinationSuccessParams struct {
	LastSuccessfulBackupAt sql.NullString `json:"last_successful_backup_at"`
	ID                     string         `json:"id"`
}

func (q *Queries) RecordBackupDestinationSuccess(ctx context.Context, arg RecordBackupDestinationSuccessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordBackupDestinationSuccess, arg.LastSuccessfulBackupAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
