// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backuprecipient.sql

package storedb

import (
	"context"
)

const getBackupRecipient = `-- name: GetBackupRecipient :one

SELECT public_recipient, wrapped_identity, check_value FROM backup_recipient WHERE id = 1
`

type GetBackupRecipientRow struct {
	PublicRecipient string `json:"public_recipient"`
	WrappedIdentity []byte `json:"wrapped_identity"`
	CheckValue      []byte `json:"check_value"`
}

// sqlc input (#275, Q60): typed Go query code for the backup_recipient
// table, generated into internal/store/db/ by `make gen`. Deliberately no
// comment other than each "-- name:" line between queries below (see
// jobs.sql for the same note about sqlc's SQLite engine).
func (q *Queries) GetBackupRecipient(ctx context.Context) (*GetBackupRecipientRow, error) {
	row := q.db.QueryRowContext(ctx, getBackupRecipient)
	var i GetBackupRecipientRow
	err := row.Scan(&i.PublicRecipient, &i.WrappedIdentity, &i.CheckValue)
	return &i, err
}

const setBackupRecipient = `-- name: SetBackupRecipient :exec
INSERT INTO backup_recipient (id, public_recipient, wrapped_identity, check_value, created_at) VALUES (1, ?, ?, ?, ?)
`

type SetBackupRecipientParams struct {
	PublicRecipient string `json:"public_recipient"`
	WrappedIdentity []byte `json:"wrapped_identity"`
	CheckValue      []byte `json:"check_value"`
	CreatedAt       string `json:"created_at"`
}

func (q *Queries) SetBackupRecipient(ctx context.Context, arg SetBackupRecipientParams) error {
	_, err := q.db.ExecContext(ctx, setBackupRecipient,
		arg.PublicRecipient,
		arg.WrappedIdentity,
		arg.CheckValue,
		arg.CreatedAt,
	)
	return err
}
