// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_sources.sql

package storedb

import (
	"context"
)

const deleteUserAddedCatalogSource = `-- name: DeleteUserAddedCatalogSource :execrows
DELETE FROM catalog_sources WHERE id = ? AND kind = 'user_added'
`

func (q *Queries) DeleteUserAddedCatalogSource(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserAddedCatalogSource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureCuratedCatalogSource = `-- name: EnsureCuratedCatalogSource :exec
INSERT INTO catalog_sources (id, url, kind, public_key, signature_verified, last_refreshed_at, added_at)
VALUES (?, ?, 'curated', '', 1, '', ?)
ON CONFLICT (id) DO NOTHING
`

type EnsureCuratedCatalogSourceParams struct {
	ID      string `json:"id"`
	Url     string `json:"url"`
	AddedAt string `json:"added_at"`
}

func (q *Queries) EnsureCuratedCatalogSource(ctx context.Context, arg EnsureCuratedCatalogSourceParams) error {
	_, err := q.db.ExecContext(ctx, ensureCuratedCatalogSource, arg.ID, arg.Url, arg.AddedAt)
	return err
}

const getCatalogSource = `-- name: GetCatalogSource :one
SELECT id, url, kind, public_key, signature_verified, last_refreshed_at, added_at
FROM catalog_sources WHERE id = ?
`

func (q *Queries) GetCatalogSource(ctx context.Context, id string) (*CatalogSource, error) {
	row := q.db.QueryRowContext(ctx, getCatalogSource, id)
	var i CatalogSource
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Kind,
		&i.PublicKey,
		&i.SignatureVerified,
		&i.LastRefreshedAt,
		&i.AddedAt,
	)
	return &i, err
}

const insertCatalogSource = `-- name: InsertCatalogSource :exec

INSERT INTO catalog_sources (id, url, kind, public_key, signature_verified, last_refreshed_at, added_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertCatalogSourceParams struct {
	ID                string `json:"id"`
	Url               string `json:"url"`
	Kind              string `json:"kind"`
	PublicKey         string `json:"public_key"`
	SignatureVerified int64  `json:"signature_verified"`
	LastRefreshedAt   string `json:"last_refreshed_at"`
	AddedAt           string `json:"added_at"`
}

// sqlc input (#283): the catalog_sources table, generated into
// internal/store/db/ by `make gen`. Doc comments live on the Go wrapper in
// internal/store/catalog_sources.go.
func (q *Queries) InsertCatalogSource(ctx context.Context, arg InsertCatalogSourceParams) error {
	_, err := q.db.ExecContext(ctx, insertCatalogSource,
		arg.ID,
		arg.Url,
		arg.Kind,
		arg.PublicKey,
		arg.SignatureVerified,
		arg.LastRefreshedAt,
		arg.AddedAt,
	)
	return err
}

const listCatalogSources = `-- name: ListCatalogSources :many
SELECT id, url, kind, public_key, signature_verified, last_refreshed_at, added_at
FROM catalog_sources
ORDER BY CASE kind WHEN 'curated' THEN 0 ELSE 1 END ASC, added_at ASC, rowid ASC
`

func (q *Queries) ListCatalogSources(ctx context.Context) ([]*CatalogSource, error) {
	rows, err := q.db.QueryContext(ctx, listCatalogSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CatalogSource
	for rows.Next() {
		var i CatalogSource
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Kind,
			&i.PublicKey,
			&i.SignatureVerified,
			&i.LastRefreshedAt,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCatalogSourceRefresh = `-- name: RecordCatalogSourceRefresh :execrows
UPDATE catalog_sources SET last_refreshed_at = ?, signature_verified = ? WHERE id = ?
`

type RecordCatalogSourceRefreshParams struct {
	LastRefreshedAt   string `json:"last_refreshed_at"`
	SignatureVerified int64  `json:"signature_verified"`
	ID                string `json:"id"`
}

func (q *Queries) RecordCatalogSourceRefresh(ctx context.Context, arg RecordCatalogSourceRefreshParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordCatalogSourceRefresh, arg.LastRefreshedAt, arg.SignatureVerified, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
