// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_settings.sql

package storedb

import (
	"context"
	"database/sql"
)

const ensureSchemaMeta = `-- name: EnsureSchemaMeta :exec
INSERT INTO schema_info (id, installation_id, created_at) VALUES (1, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type EnsureSchemaMetaParams struct {
	InstallationID string `json:"installation_id"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) EnsureSchemaMeta(ctx context.Context, arg EnsureSchemaMetaParams) error {
	_, err := q.db.ExecContext(ctx, ensureSchemaMeta, arg.InstallationID, arg.CreatedAt)
	return err
}

const getCatalogSettings = `-- name: GetCatalogSettings :one
SELECT catalog_refresh_interval, catalog_check_on_open FROM schema_info WHERE id = 1
`

type GetCatalogSettingsRow struct {
	CatalogRefreshInterval string `json:"catalog_refresh_interval"`
	CatalogCheckOnOpen     int64  `json:"catalog_check_on_open"`
}

func (q *Queries) GetCatalogSettings(ctx context.Context) (*GetCatalogSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getCatalogSettings)
	var i GetCatalogSettingsRow
	err := row.Scan(&i.CatalogRefreshInterval, &i.CatalogCheckOnOpen)
	return &i, err
}

const updateCatalogSettings = `-- name: UpdateCatalogSettings :exec
UPDATE schema_info
SET catalog_refresh_interval = COALESCE(?1, catalog_refresh_interval),
    catalog_check_on_open = COALESCE(?2, catalog_check_on_open)
WHERE id = 1
`

type UpdateCatalogSettingsParams struct {
	RefreshInterval sql.NullString `json:"refresh_interval"`
	CheckOnOpen     sql.NullInt64  `json:"check_on_open"`
}

func (q *Queries) UpdateCatalogSettings(ctx context.Context, arg UpdateCatalogSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateCatalogSettings, arg.RefreshInterval, arg.CheckOnOpen)
	return err
}
