// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: container_updates.sql

package storedb

import (
	"context"
)

const deleteContainerImageHistory = `-- name: DeleteContainerImageHistory :exec
DELETE FROM container_image_history WHERE id = ?
`

func (q *Queries) DeleteContainerImageHistory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteContainerImageHistory, id)
	return err
}

const getContainerUpdateSettings = `-- name: GetContainerUpdateSettings :one
SELECT image_keep_days FROM container_update_settings WHERE id = 1
`

func (q *Queries) GetContainerUpdateSettings(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getContainerUpdateSettings)
	var image_keep_days int64
	err := row.Scan(&image_keep_days)
	return image_keep_days, err
}

const getLatestContainerImageHistory = `-- name: GetLatestContainerImageHistory :one
SELECT id, container, image, previous_image_id, snapshot_archive, snapshot_destination,
       updated_at, keep_until, reverted_at, snapshot_restored_at
FROM container_image_history WHERE container = ? ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetLatestContainerImageHistory(ctx context.Context, container string) (*ContainerImageHistory, error) {
	row := q.db.QueryRowContext(ctx, getLatestContainerImageHistory, container)
	var i ContainerImageHistory
	err := row.Scan(
		&i.ID,
		&i.Container,
		&i.Image,
		&i.PreviousImageID,
		&i.SnapshotArchive,
		&i.SnapshotDestination,
		&i.UpdatedAt,
		&i.KeepUntil,
		&i.RevertedAt,
		&i.SnapshotRestoredAt,
	)
	return &i, err
}

const insertContainerImageHistory = `-- name: InsertContainerImageHistory :one

INSERT INTO container_image_history (
    container, image, previous_image_id, snapshot_archive, snapshot_destination,
    updated_at, keep_until, reverted_at
) VALUES (?, ?, ?, ?, ?, ?, ?, '')
RETURNING id
`

type InsertContainerImageHistoryParams struct {
	Container           string `json:"container"`
	Image               string `json:"image"`
	PreviousImageID     string `json:"previous_image_id"`
	SnapshotArchive     string `json:"snapshot_archive"`
	SnapshotDestination string `json:"snapshot_destination"`
	UpdatedAt           string `json:"updated_at"`
	KeepUntil           string `json:"keep_until"`
}

// sqlc input (#284): container update history, the bulk-update opt-out and
// the update settings, generated into internal/store/db/ by `make gen`. Doc
// comments live on the Go wrapper in internal/store/image_history.go.
func (q *Queries) InsertContainerImageHistory(ctx context.Context, arg InsertContainerImageHistoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertContainerImageHistory,
		arg.Container,
		arg.Image,
		arg.PreviousImageID,
		arg.SnapshotArchive,
		arg.SnapshotDestination,
		arg.UpdatedAt,
		arg.KeepUntil,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listBulkExcludedContainers = `-- name: ListBulkExcludedContainers :many
SELECT container FROM container_update_policy WHERE bulk_excluded = 1 ORDER BY container ASC
`

func (q *Queries) ListBulkExcludedContainers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listBulkExcludedContainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var container string
		if err := rows.Scan(&container); err != nil {
			return nil, err
		}
		items = append(items, container)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContainerImageHistory = `-- name: ListContainerImageHistory :many
SELECT id, container, image, previous_image_id, snapshot_archive, snapshot_destination,
       updated_at, keep_until, reverted_at, snapshot_restored_at
FROM container_image_history ORDER BY id DESC
`

func (q *Queries) ListContainerImageHistory(ctx context.Context) ([]*ContainerImageHistory, error) {
	rows, err := q.db.QueryContext(ctx, listContainerImageHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ContainerImageHistory
	for rows.Next() {
		var i ContainerImageHistory
		if err := rows.Scan(
			&i.ID,
			&i.Container,
			&i.Image,
			&i.PreviousImageID,
			&i.SnapshotArchive,
			&i.SnapshotDestination,
			&i.UpdatedAt,
			&i.KeepUntil,
			&i.RevertedAt,
			&i.SnapshotRestoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markContainerImageHistoryReverted = `-- name: MarkContainerImageHistoryReverted :execrows
UPDATE container_image_history SET reverted_at = ? WHERE id = ? AND reverted_at = ''
`

type MarkContainerImageHistoryRevertedParams struct {
	RevertedAt string `json:"reverted_at"`
	ID         int64  `json:"id"`
}

func (q *Queries) MarkContainerImageHistoryReverted(ctx context.Context, arg MarkContainerImageHistoryRevertedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markContainerImageHistoryReverted, arg.RevertedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markContainerImageHistorySnapshotRestored = `-- name: MarkContainerImageHistorySnapshotRestored :execrows
UPDATE container_image_history SET snapshot_restored_at = ? WHERE id = ? AND reverted_at = ''
`

type MarkContainerImageHistorySnapshotRestoredParams struct {
	SnapshotRestoredAt string `json:"snapshot_restored_at"`
	ID                 int64  `json:"id"`
}

func (q *Queries) MarkContainerImageHistorySnapshotRestored(ctx context.Context, arg MarkContainerImageHistorySnapshotRestoredParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markContainerImageHistorySnapshotRestored, arg.SnapshotRestoredAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setContainerUpdatePolicy = `-- name: SetContainerUpdatePolicy :exec
INSERT INTO container_update_policy (container, bulk_excluded) VALUES (?, ?)
ON CONFLICT (container) DO UPDATE SET bulk_excluded = excluded.bulk_excluded
`

type SetContainerUpdatePolicyParams struct {
	Container    string `json:"container"`
	BulkExcluded int64  `json:"bulk_excluded"`
}

func (q *Queries) SetContainerUpdatePolicy(ctx context.Context, arg SetContainerUpdatePolicyParams) error {
	_, err := q.db.ExecContext(ctx, setContainerUpdatePolicy, arg.Container, arg.BulkExcluded)
	return err
}

const setContainerUpdateSettings = `-- name: SetContainerUpdateSettings :exec
INSERT INTO container_update_settings (id, image_keep_days) VALUES (1, ?)
ON CONFLICT (id) DO UPDATE SET image_keep_days = excluded.image_keep_days
`

func (q *Queries) SetContainerUpdateSettings(ctx context.Context, imageKeepDays int64) error {
	_, err := q.db.ExecContext(ctx, setContainerUpdateSettings, imageKeepDays)
	return err
}
