// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: external.sql

package storedb

import (
	"context"
	"database/sql"
)

const deleteExternalDisk = `-- name: DeleteExternalDisk :execrows
DELETE FROM external_disks WHERE label = ?
`

func (q *Queries) DeleteExternalDisk(ctx context.Context, label string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExternalDisk, label)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getExternalDiskByDevice = `-- name: GetExternalDiskByDevice :one
SELECT
    id, label, device, filesystem, fs_uuid,
    wwn, serial, by_id_name, weak_identity, mountpoint, backup_destination
FROM external_disks WHERE device = ?
`

func (q *Queries) GetExternalDiskByDevice(ctx context.Context, device string) (*ExternalDisk, error) {
	row := q.db.QueryRowContext(ctx, getExternalDiskByDevice, device)
	var i ExternalDisk
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Device,
		&i.Filesystem,
		&i.FsUuid,
		&i.Wwn,
		&i.Serial,
		&i.ByIDName,
		&i.WeakIdentity,
		&i.Mountpoint,
		&i.BackupDestination,
	)
	return &i, err
}

const getExternalDiskByLabel = `-- name: GetExternalDiskByLabel :one
SELECT
    id, label, device, filesystem, fs_uuid,
    wwn, serial, by_id_name, weak_identity, mountpoint, backup_destination
FROM external_disks WHERE label = ?
`

func (q *Queries) GetExternalDiskByLabel(ctx context.Context, label string) (*ExternalDisk, error) {
	row := q.db.QueryRowContext(ctx, getExternalDiskByLabel, label)
	var i ExternalDisk
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Device,
		&i.Filesystem,
		&i.FsUuid,
		&i.Wwn,
		&i.Serial,
		&i.ByIDName,
		&i.WeakIdentity,
		&i.Mountpoint,
		&i.BackupDestination,
	)
	return &i, err
}

const insertExternalDisk = `-- name: InsertExternalDisk :exec

INSERT INTO external_disks (
    label, device, filesystem, fs_uuid,
    wwn, serial, by_id_name, weak_identity, mountpoint, backup_destination
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?
)
`

type InsertExternalDiskParams struct {
	Label             string         `json:"label"`
	Device            string         `json:"device"`
	Filesystem        string         `json:"filesystem"`
	FsUuid            string         `json:"fs_uuid"`
	Wwn               sql.NullString `json:"wwn"`
	Serial            sql.NullString `json:"serial"`
	ByIDName          sql.NullString `json:"by_id_name"`
	WeakIdentity      int64          `json:"weak_identity"`
	Mountpoint        string         `json:"mountpoint"`
	BackupDestination int64          `json:"backup_destination"`
}

// sqlc input (#115, Q72): typed Go query code for the external_disks
// table, generated into internal/store/db/ by `make gen`. Deliberately no
// comment other than each "-- name:" line between queries below (see
// jobs.sql). Doc comments live on the hand-written Go wrapper in
// internal/store/external.go instead.
func (q *Queries) InsertExternalDisk(ctx context.Context, arg InsertExternalDiskParams) error {
	_, err := q.db.ExecContext(ctx, insertExternalDisk,
		arg.Label,
		arg.Device,
		arg.Filesystem,
		arg.FsUuid,
		arg.Wwn,
		arg.Serial,
		arg.ByIDName,
		arg.WeakIdentity,
		arg.Mountpoint,
		arg.BackupDestination,
	)
	return err
}

const listExternalDisks = `-- name: ListExternalDisks :many
SELECT
    id, label, device, filesystem, fs_uuid,
    wwn, serial, by_id_name, weak_identity, mountpoint, backup_destination
FROM external_disks
ORDER BY label ASC
`

func (q *Queries) ListExternalDisks(ctx context.Context) ([]*ExternalDisk, error) {
	rows, err := q.db.QueryContext(ctx, listExternalDisks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ExternalDisk
	for rows.Next() {
		var i ExternalDisk
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Device,
			&i.Filesystem,
			&i.FsUuid,
			&i.Wwn,
			&i.Serial,
			&i.ByIDName,
			&i.WeakIdentity,
			&i.Mountpoint,
			&i.BackupDestination,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setExternalBackupDestination = `-- name: SetExternalBackupDestination :execrows
UPDATE external_disks
SET backup_destination = ?
WHERE label = ?
`

type SetExternalBackupDestinationParams struct {
	BackupDestination int64  `json:"backup_destination"`
	Label             string `json:"label"`
}

func (q *Queries) SetExternalBackupDestination(ctx context.Context, arg SetExternalBackupDestinationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setExternalBackupDestination, arg.BackupDestination, arg.Label)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateExternalDisk = `-- name: UpdateExternalDisk :execrows
UPDATE external_disks
SET device = ?, filesystem = ?, fs_uuid = ?,
    wwn = ?, serial = ?, by_id_name = ?, weak_identity = ?,
    mountpoint = ?, backup_destination = ?
WHERE label = ?
`

type UpdateExternalDiskParams struct {
	Device            string         `json:"device"`
	Filesystem        string         `json:"filesystem"`
	FsUuid            string         `json:"fs_uuid"`
	Wwn               sql.NullString `json:"wwn"`
	Serial            sql.NullString `json:"serial"`
	ByIDName          sql.NullString `json:"by_id_name"`
	WeakIdentity      int64          `json:"weak_identity"`
	Mountpoint        string         `json:"mountpoint"`
	BackupDestination int64          `json:"backup_destination"`
	Label             string         `json:"label"`
}

func (q *Queries) UpdateExternalDisk(ctx context.Context, arg UpdateExternalDiskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateExternalDisk,
		arg.Device,
		arg.Filesystem,
		arg.FsUuid,
		arg.Wwn,
		arg.Serial,
		arg.ByIDName,
		arg.WeakIdentity,
		arg.Mountpoint,
		arg.BackupDestination,
		arg.Label,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
