// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_metadata.sql

package storedb

import (
	"context"
)

const deleteFileMetadataOtherGenerations = `-- name: DeleteFileMetadataOtherGenerations :execrows
DELETE FROM file_metadata
WHERE (file_metadata.generation, file_metadata.disk_mountpoint, file_metadata.rel_path) IN (
    SELECT s.generation, s.disk_mountpoint, s.rel_path
    FROM file_metadata s
    WHERE s.generation < ?1 OR s.generation > ?1
    LIMIT ?2
)
`

type DeleteFileMetadataOtherGenerationsParams struct {
	Generation int64 `json:"generation"`
	Limit      int64 `json:"limit"`
}

func (q *Queries) DeleteFileMetadataOtherGenerations(ctx context.Context, arg DeleteFileMetadataOtherGenerationsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFileMetadataOtherGenerations, arg.Generation, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFileMetadata = `-- name: GetFileMetadata :one
SELECT m.is_dir, m.uid, m.gid, m.mode
FROM file_metadata m
JOIN file_metadata_current c ON c.generation = m.generation
WHERE c.id = 1 AND m.disk_mountpoint = ? AND m.rel_path = ?
`

type GetFileMetadataParams struct {
	DiskMountpoint string `json:"disk_mountpoint"`
	RelPath        string `json:"rel_path"`
}

type GetFileMetadataRow struct {
	IsDir int64 `json:"is_dir"`
	Uid   int64 `json:"uid"`
	Gid   int64 `json:"gid"`
	Mode  int64 `json:"mode"`
}

func (q *Queries) GetFileMetadata(ctx context.Context, arg GetFileMetadataParams) (*GetFileMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getFileMetadata, arg.DiskMountpoint, arg.RelPath)
	var i GetFileMetadataRow
	err := row.Scan(
		&i.IsDir,
		&i.Uid,
		&i.Gid,
		&i.Mode,
	)
	return &i, err
}

const getFileMetadataGeneration = `-- name: GetFileMetadataGeneration :one
SELECT generation FROM file_metadata_current WHERE id = 1
`

func (q *Queries) GetFileMetadataGeneration(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFileMetadataGeneration)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const insertFileMetadata = `-- name: InsertFileMetadata :exec

INSERT INTO file_metadata (generation, disk_mountpoint, rel_path, is_dir, uid, gid, mode)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertFileMetadataParams struct {
	Generation     int64  `json:"generation"`
	DiskMountpoint string `json:"disk_mountpoint"`
	RelPath        string `json:"rel_path"`
	IsDir          int64  `json:"is_dir"`
	Uid            int64  `json:"uid"`
	Gid            int64  `json:"gid"`
	Mode           int64  `json:"mode"`
}

// sqlc input (#626): typed Go query code for the file_metadata and
// file_metadata_current tables, generated into internal/store/db/ by
// `make gen`. Doc comments live on the hand-written Go wrapper in
// internal/parity/filemeta_store.go instead.
func (q *Queries) InsertFileMetadata(ctx context.Context, arg InsertFileMetadataParams) error {
	_, err := q.db.ExecContext(ctx, insertFileMetadata,
		arg.Generation,
		arg.DiskMountpoint,
		arg.RelPath,
		arg.IsDir,
		arg.Uid,
		arg.Gid,
		arg.Mode,
	)
	return err
}

const maxFileMetadataGeneration = `-- name: MaxFileMetadataGeneration :one
SELECT CAST(COALESCE(MAX(generation), 0) AS INTEGER) FROM file_metadata
`

func (q *Queries) MaxFileMetadataGeneration(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxFileMetadataGeneration)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setFileMetadataGeneration = `-- name: SetFileMetadataGeneration :exec
INSERT INTO file_metadata_current (id, generation) VALUES (1, ?)
ON CONFLICT (id) DO UPDATE SET generation = excluded.generation
`

func (q *Queries) SetFileMetadataGeneration(ctx context.Context, generation int64) error {
	_, err := q.db.ExecContext(ctx, setFileMetadataGeneration, generation)
	return err
}
