// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: host_config.sql

package storedb

import (
	"context"
)

const getHostConfig = `-- name: GetHostConfig :one
SELECT kind, decision, facts, applied_at
FROM host_config WHERE kind = ?
`

func (q *Queries) GetHostConfig(ctx context.Context, kind string) (*HostConfig, error) {
	row := q.db.QueryRowContext(ctx, getHostConfig, kind)
	var i HostConfig
	err := row.Scan(
		&i.Kind,
		&i.Decision,
		&i.Facts,
		&i.AppliedAt,
	)
	return &i, err
}

const listHostConfig = `-- name: ListHostConfig :many
SELECT kind, decision, facts, applied_at
FROM host_config
ORDER BY kind
`

func (q *Queries) ListHostConfig(ctx context.Context) ([]*HostConfig, error) {
	rows, err := q.db.QueryContext(ctx, listHostConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*HostConfig
	for rows.Next() {
		var i HostConfig
		if err := rows.Scan(
			&i.Kind,
			&i.Decision,
			&i.Facts,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHostConfig = `-- name: UpsertHostConfig :exec

INSERT INTO host_config (kind, decision, facts, applied_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(kind) DO UPDATE SET
    decision = excluded.decision,
    facts = excluded.facts,
    applied_at = excluded.applied_at
`

type UpsertHostConfigParams struct {
	Kind      string `json:"kind"`
	Decision  string `json:"decision"`
	Facts     string `json:"facts"`
	AppliedAt string `json:"applied_at"`
}

// sqlc input (Q76): typed Go query code for the host_config table,
// generated into internal/store/db/ by `make gen`. Doc comments live on
// the hand-written Go wrapper in internal/store/host.go instead.
func (q *Queries) UpsertHostConfig(ctx context.Context, arg UpsertHostConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertHostConfig,
		arg.Kind,
		arg.Decision,
		arg.Facts,
		arg.AppliedAt,
	)
	return err
}
