// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package storedb

import (
	"context"
	"database/sql"
)

const createJob = `-- name: CreateJob :exec

INSERT INTO jobs (
    id, "type", class, "status", progress, resumable, cancellable,
    resource_ids, checkpoint, error_code, error_message,
    created_at, started_at, finished_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?
)
`

type CreateJobParams struct {
	ID           string         `json:"id"`
	Type         string         `json:"type"`
	Class        string         `json:"class"`
	Status       string         `json:"status"`
	Progress     sql.NullInt64  `json:"progress"`
	Resumable    int64          `json:"resumable"`
	Cancellable  int64          `json:"cancellable"`
	ResourceIds  sql.NullString `json:"resource_ids"`
	Checkpoint   []byte         `json:"checkpoint"`
	ErrorCode    sql.NullString `json:"error_code"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    string         `json:"created_at"`
	StartedAt    sql.NullString `json:"started_at"`
	FinishedAt   sql.NullString `json:"finished_at"`
}

// sqlc input (#19, Q60): typed Go query code for the jobs table, generated
// into internal/store/db/ by `make gen`. Nothing hand-writes that package.
// Deliberately no comment other than each "-- name:" line between queries
// below: sqlc v1.31.1's SQLite engine mis-slices the raw source once any
// extra comment line appears between two queries, silently truncating the
// generated SQL text of every query that follows (confirmed while writing
// this file). ListJobs, ListActiveJobs and InterruptActiveJobs carry doc
// comments on their Go methods instead, in jobs.go, immediately above
// each hand-written wrapper that calls them.
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob,
		arg.ID,
		arg.Type,
		arg.Class,
		arg.Status,
		arg.Progress,
		arg.Resumable,
		arg.Cancellable,
		arg.ResourceIds,
		arg.Checkpoint,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const getJob = `-- name: GetJob :one
SELECT
    id, "type", class, "status", progress, resumable, cancellable,
    resource_ids, checkpoint, error_code, error_message,
    created_at, started_at, finished_at
FROM jobs WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (*Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Class,
		&i.Status,
		&i.Progress,
		&i.Resumable,
		&i.Cancellable,
		&i.ResourceIds,
		&i.Checkpoint,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const interruptActiveJobs = `-- name: InterruptActiveJobs :exec
UPDATE jobs SET "status" = 'interrupted', finished_at = ?
WHERE "status" IN ('queued', 'running')
`

func (q *Queries) InterruptActiveJobs(ctx context.Context, finishedAt sql.NullString) error {
	_, err := q.db.ExecContext(ctx, interruptActiveJobs, finishedAt)
	return err
}

const listActiveJobs = `-- name: ListActiveJobs :many
SELECT
    id, "type", class, "status", progress, resumable, cancellable,
    resource_ids, checkpoint, error_code, error_message,
    created_at, started_at, finished_at
FROM jobs WHERE "status" IN ('queued', 'running') ORDER BY created_at ASC
`

func (q *Queries) ListActiveJobs(ctx context.Context) ([]*Job, error) {
	rows, err := q.db.QueryContext(ctx, listActiveJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Class,
			&i.Status,
			&i.Progress,
			&i.Resumable,
			&i.Cancellable,
			&i.ResourceIds,
			&i.Checkpoint,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT
    id, "type", class, "status", progress, resumable, cancellable,
    resource_ids, checkpoint, error_code, error_message,
    created_at, started_at, finished_at
FROM jobs
WHERE (?1 IS NULL OR class = ?1)
  AND (?2 IS NULL OR "status" = ?2)
ORDER BY created_at DESC
LIMIT ?3
`

type ListJobsParams struct {
	Class    interface{} `json:"class"`
	Status   interface{} `json:"status"`
	RowLimit int64       `json:"row_limit"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]*Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, arg.Class, arg.Status, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Class,
			&i.Status,
			&i.Progress,
			&i.Resumable,
			&i.Cancellable,
			&i.ResourceIds,
			&i.Checkpoint,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveJobCheckpoint = `-- name: SaveJobCheckpoint :exec
UPDATE jobs SET checkpoint = ? WHERE id = ?
`

type SaveJobCheckpointParams struct {
	Checkpoint []byte `json:"checkpoint"`
	ID         string `json:"id"`
}

func (q *Queries) SaveJobCheckpoint(ctx context.Context, arg SaveJobCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, saveJobCheckpoint, arg.Checkpoint, arg.ID)
	return err
}

const updateJobProgress = `-- name: UpdateJobProgress :exec
UPDATE jobs SET progress = ? WHERE id = ?
`

type UpdateJobProgressParams struct {
	Progress sql.NullInt64 `json:"progress"`
	ID       string        `json:"id"`
}

func (q *Queries) UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateJobProgress, arg.Progress, arg.ID)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET "status" = ?, progress = ?, error_code = ?, error_message = ?,
    started_at = ?, finished_at = ?
WHERE id = ?
`

type UpdateJobStatusParams struct {
	Status       string         `json:"status"`
	Progress     sql.NullInt64  `json:"progress"`
	ErrorCode    sql.NullString `json:"error_code"`
	ErrorMessage sql.NullString `json:"error_message"`
	StartedAt    sql.NullString `json:"started_at"`
	FinishedAt   sql.NullString `json:"finished_at"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus,
		arg.Status,
		arg.Progress,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
