// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: machinekey.sql

package storedb

import (
	"context"
)

const getMachineKeyCheck = `-- name: GetMachineKeyCheck :one

SELECT check_value FROM machine_key_check WHERE id = 1
`

// sqlc input (#22, Q60): typed Go query code for the machine_key_check
// table, generated into internal/store/db/ by `make gen`. Deliberately no
// comment other than each "-- name:" line between queries below (see
// jobs.sql for the same note about sqlc's SQLite engine).
func (q *Queries) GetMachineKeyCheck(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getMachineKeyCheck)
	var check_value []byte
	err := row.Scan(&check_value)
	return check_value, err
}

const setMachineKeyCheck = `-- name: SetMachineKeyCheck :exec
INSERT INTO machine_key_check (id, check_value, created_at) VALUES (1, ?, ?)
`

type SetMachineKeyCheckParams struct {
	CheckValue []byte `json:"check_value"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) SetMachineKeyCheck(ctx context.Context, arg SetMachineKeyCheckParams) error {
	_, err := q.db.ExecContext(ctx, setMachineKeyCheck, arg.CheckValue, arg.CreatedAt)
	return err
}
