// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migration_session.sql

package storedb

import (
	"context"
)

const clearMigrationSession = `-- name: ClearMigrationSession :exec
UPDATE migration_session SET
    source_file = '', source_size = 0, source_received_at = '', report = '',
    scan_file = '', scan_size = 0, scan_received_at = '', scan_unverified_layout = 0,
    scan_error = '', scan_full_checksums = 0, verify = ''
WHERE id = 1
`

func (q *Queries) ClearMigrationSession(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearMigrationSession)
	return err
}

const deleteMigrationSession = `-- name: DeleteMigrationSession :exec
DELETE FROM migration_session WHERE id = 1 AND checklist = ''
`

func (q *Queries) DeleteMigrationSession(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteMigrationSession)
	return err
}

const getMigrationSession = `-- name: GetMigrationSession :one

SELECT source_file, source_size, source_received_at, report,
       scan_file, scan_size, scan_received_at, scan_unverified_layout, scan_error, scan_full_checksums, verify, checklist
FROM migration_session
WHERE id = 1
`

type GetMigrationSessionRow struct {
	SourceFile           string `json:"source_file"`
	SourceSize           int64  `json:"source_size"`
	SourceReceivedAt     string `json:"source_received_at"`
	Report               string `json:"report"`
	ScanFile             string `json:"scan_file"`
	ScanSize             int64  `json:"scan_size"`
	ScanReceivedAt       string `json:"scan_received_at"`
	ScanUnverifiedLayout int64  `json:"scan_unverified_layout"`
	ScanError            string `json:"scan_error"`
	ScanFullChecksums    int64  `json:"scan_full_checksums"`
	Verify               string `json:"verify"`
	Checklist            string `json:"checklist"`
}

// sqlc input (#75): the one Unraid migration session, generated into
// internal/store/db/ by `make gen`.
func (q *Queries) GetMigrationSession(ctx context.Context) (*GetMigrationSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getMigrationSession)
	var i GetMigrationSessionRow
	err := row.Scan(
		&i.SourceFile,
		&i.SourceSize,
		&i.SourceReceivedAt,
		&i.Report,
		&i.ScanFile,
		&i.ScanSize,
		&i.ScanReceivedAt,
		&i.ScanUnverifiedLayout,
		&i.ScanError,
		&i.ScanFullChecksums,
		&i.Verify,
		&i.Checklist,
	)
	return &i, err
}

const setMigrationSessionChecklist = `-- name: SetMigrationSessionChecklist :exec
INSERT INTO migration_session (id, checklist) VALUES (1, ?)
ON CONFLICT (id) DO UPDATE SET checklist = excluded.checklist
`

func (q *Queries) SetMigrationSessionChecklist(ctx context.Context, checklist string) error {
	_, err := q.db.ExecContext(ctx, setMigrationSessionChecklist, checklist)
	return err
}

const upsertMigrationSession = `-- name: UpsertMigrationSession :exec
INSERT INTO migration_session (
    id, source_file, source_size, source_received_at, report,
    scan_file, scan_size, scan_received_at, scan_unverified_layout, scan_error, scan_full_checksums, verify
) VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    source_file = excluded.source_file,
    source_size = excluded.source_size,
    source_received_at = excluded.source_received_at,
    report = excluded.report,
    scan_file = excluded.scan_file,
    scan_size = excluded.scan_size,
    scan_received_at = excluded.scan_received_at,
    scan_unverified_layout = excluded.scan_unverified_layout,
    scan_error = excluded.scan_error,
    scan_full_checksums = excluded.scan_full_checksums,
    verify = excluded.verify
`

type UpsertMigrationSessionParams struct {
	SourceFile           string `json:"source_file"`
	SourceSize           int64  `json:"source_size"`
	SourceReceivedAt     string `json:"source_received_at"`
	Report               string `json:"report"`
	ScanFile             string `json:"scan_file"`
	ScanSize             int64  `json:"scan_size"`
	ScanReceivedAt       string `json:"scan_received_at"`
	ScanUnverifiedLayout int64  `json:"scan_unverified_layout"`
	ScanError            string `json:"scan_error"`
	ScanFullChecksums    int64  `json:"scan_full_checksums"`
	Verify               string `json:"verify"`
}

func (q *Queries) UpsertMigrationSession(ctx context.Context, arg UpsertMigrationSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertMigrationSession,
		arg.SourceFile,
		arg.SourceSize,
		arg.SourceReceivedAt,
		arg.Report,
		arg.ScanFile,
		arg.ScanSize,
		arg.ScanReceivedAt,
		arg.ScanUnverifiedLayout,
		arg.ScanError,
		arg.ScanFullChecksums,
		arg.Verify,
	)
	return err
}
