// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"database/sql"
)

type AuditLog struct {
	ID     int64          `json:"id"`
	Actor  string         `json:"actor"`
	Action string         `json:"action"`
	Detail sql.NullString `json:"detail"`
	At     string         `json:"at"`
}

type Job struct {
	ID           string         `json:"id"`
	Type         string         `json:"type"`
	Class        string         `json:"class"`
	Status       string         `json:"status"`
	Progress     sql.NullInt64  `json:"progress"`
	Resumable    int64          `json:"resumable"`
	Cancellable  int64          `json:"cancellable"`
	ResourceIds  sql.NullString `json:"resource_ids"`
	Checkpoint   []byte         `json:"checkpoint"`
	ErrorCode    sql.NullString `json:"error_code"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    string         `json:"created_at"`
	StartedAt    sql.NullString `json:"started_at"`
	FinishedAt   sql.NullString `json:"finished_at"`
	Params       sql.NullString `json:"params"`
}

type MachineKeyCheck struct {
	ID         int64  `json:"id"`
	CheckValue []byte `json:"check_value"`
	CreatedAt  string `json:"created_at"`
}

type NotifyChannel struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Enabled   int64  `json:"enabled"`
	Config    string `json:"config"`
	Secret    []byte `json:"secret"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type NotifyDelivery struct {
	ID            string         `json:"id"`
	ChannelID     string         `json:"channel_id"`
	EventType     string         `json:"event_type"`
	Severity      string         `json:"severity"`
	Title         string         `json:"title"`
	Message       string         `json:"message"`
	Status        string         `json:"status"`
	Attempts      int64          `json:"attempts"`
	LastError     sql.NullString `json:"last_error"`
	CreatedAt     string         `json:"created_at"`
	NextAttemptAt string         `json:"next_attempt_at"`
	DeliveredAt   sql.NullString `json:"delivered_at"`
}

type NotifyEventSeverity struct {
	EventType string `json:"event_type"`
	Severity  string `json:"severity"`
}

type NotifyQuietHour struct {
	ID        int64  `json:"id"`
	Enabled   int64  `json:"enabled"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
	UpdatedAt string `json:"updated_at"`
}

type NotifyRoute struct {
	EventType string `json:"event_type"`
	ChannelID string `json:"channel_id"`
}

type SchemaInfo struct {
	ID               int64          `json:"id"`
	InstallationID   string         `json:"installation_id"`
	CreatedAt        string         `json:"created_at"`
	Hostname         sql.NullString `json:"hostname"`
	Timezone         sql.NullString `json:"timezone"`
	BackupPassphrase []byte         `json:"backup_passphrase"`
}

type Session struct {
	TokenHash string `json:"token_hash"`
	UserID    string `json:"user_id"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type SpinEvent struct {
	ID        int64  `json:"id"`
	Device    string `json:"device"`
	FromState string `json:"from_state"`
	ToState   string `json:"to_state"`
	At        string `json:"at"`
}

type User struct {
	ID                string         `json:"id"`
	Username          string         `json:"username"`
	PasswordHash      string         `json:"password_hash"`
	Role              string         `json:"role"`
	TotpSecret        []byte         `json:"totp_secret"`
	TotpConfirmedAt   sql.NullString `json:"totp_confirmed_at"`
	TotpLastStep      int64          `json:"totp_last_step"`
	CreatedAt         string         `json:"created_at"`
	TotpPendingSecret []byte         `json:"totp_pending_secret"`
}
