// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"database/sql"
)

type Job struct {
	ID           string         `json:"id"`
	Type         string         `json:"type"`
	Class        string         `json:"class"`
	Status       string         `json:"status"`
	Progress     sql.NullInt64  `json:"progress"`
	Resumable    int64          `json:"resumable"`
	Cancellable  int64          `json:"cancellable"`
	ResourceIds  sql.NullString `json:"resource_ids"`
	Checkpoint   []byte         `json:"checkpoint"`
	ErrorCode    sql.NullString `json:"error_code"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    string         `json:"created_at"`
	StartedAt    sql.NullString `json:"started_at"`
	FinishedAt   sql.NullString `json:"finished_at"`
}

type MachineKeyCheck struct {
	ID         int64  `json:"id"`
	CheckValue []byte `json:"check_value"`
	CreatedAt  string `json:"created_at"`
}

type SchemaInfo struct {
	ID             int64  `json:"id"`
	InstallationID string `json:"installation_id"`
	CreatedAt      string `json:"created_at"`
}

type Session struct {
	TokenHash string `json:"token_hash"`
	UserID    string `json:"user_id"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type User struct {
	ID                string         `json:"id"`
	Username          string         `json:"username"`
	PasswordHash      string         `json:"password_hash"`
	Role              string         `json:"role"`
	TotpSecret        []byte         `json:"totp_secret"`
	TotpConfirmedAt   sql.NullString `json:"totp_confirmed_at"`
	TotpLastStep      int64          `json:"totp_last_step"`
	CreatedAt         string         `json:"created_at"`
	TotpPendingSecret []byte         `json:"totp_pending_secret"`
}
