// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notify.sql

package storedb

import (
	"context"
	"database/sql"
	"strings"
)

const countUnreadAlerts = `-- name: CountUnreadAlerts :one
SELECT COUNT(*) FROM notify_alerts WHERE read_at IS NULL
`

func (q *Queries) CountUnreadAlerts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadAlerts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlert = `-- name: CreateAlert :exec
INSERT INTO notify_alerts (
    id, event_type, severity, title, message, created_at, read_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
`

type CreateAlertParams struct {
	ID        string         `json:"id"`
	EventType string         `json:"event_type"`
	Severity  string         `json:"severity"`
	Title     string         `json:"title"`
	Message   string         `json:"message"`
	CreatedAt string         `json:"created_at"`
	ReadAt    sql.NullString `json:"read_at"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) error {
	_, err := q.db.ExecContext(ctx, createAlert,
		arg.ID,
		arg.EventType,
		arg.Severity,
		arg.Title,
		arg.Message,
		arg.CreatedAt,
		arg.ReadAt,
	)
	return err
}

const createChannel = `-- name: CreateChannel :exec

INSERT INTO notify_channels (
    id, name, "type", enabled, config, secret, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateChannelParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Enabled   int64  `json:"enabled"`
	Config    string `json:"config"`
	Secret    []byte `json:"secret"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// sqlc input (#35, Q60): typed Go query code for the notify_channels,
// notify_routes, notify_event_severity, notify_quiet_hours and
// notify_deliveries tables, generated into internal/store/db/ by
// `make gen`. Deliberately no comment other than each "-- name:" line
// between queries below (see jobs.sql for the same note about sqlc's
// SQLite engine mis-slicing raw source around extra comment lines). Doc
// comments live on the hand-written Go wrapper in internal/notify/store.go
// instead.
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) error {
	_, err := q.db.ExecContext(ctx, createChannel,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Enabled,
		arg.Config,
		arg.Secret,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createDelivery = `-- name: CreateDelivery :exec
INSERT INTO notify_deliveries (
    id, channel_id, event_type, severity, title, message,
    "status", attempts, last_error, created_at, next_attempt_at, delivered_at
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?
)
`

type CreateDeliveryParams struct {
	ID            string         `json:"id"`
	ChannelID     string         `json:"channel_id"`
	EventType     string         `json:"event_type"`
	Severity      string         `json:"severity"`
	Title         string         `json:"title"`
	Message       string         `json:"message"`
	Status        string         `json:"status"`
	Attempts      int64          `json:"attempts"`
	LastError     sql.NullString `json:"last_error"`
	CreatedAt     string         `json:"created_at"`
	NextAttemptAt string         `json:"next_attempt_at"`
	DeliveredAt   sql.NullString `json:"delivered_at"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, createDelivery,
		arg.ID,
		arg.ChannelID,
		arg.EventType,
		arg.Severity,
		arg.Title,
		arg.Message,
		arg.Status,
		arg.Attempts,
		arg.LastError,
		arg.CreatedAt,
		arg.NextAttemptAt,
		arg.DeliveredAt,
	)
	return err
}

const deleteChannel = `-- name: DeleteChannel :execrows
DELETE FROM notify_channels WHERE id = ?
`

func (q *Queries) DeleteChannel(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDeliveriesForChannel = `-- name: DeleteDeliveriesForChannel :exec
DELETE FROM notify_deliveries WHERE channel_id = ?
`

func (q *Queries) DeleteDeliveriesForChannel(ctx context.Context, channelID string) error {
	_, err := q.db.ExecContext(ctx, deleteDeliveriesForChannel, channelID)
	return err
}

const deleteRoutesForChannel = `-- name: DeleteRoutesForChannel :exec
DELETE FROM notify_routes WHERE channel_id = ?
`

func (q *Queries) DeleteRoutesForChannel(ctx context.Context, channelID string) error {
	_, err := q.db.ExecContext(ctx, deleteRoutesForChannel, channelID)
	return err
}

const deleteRoutesForEvent = `-- name: DeleteRoutesForEvent :exec
DELETE FROM notify_routes WHERE event_type = ?
`

func (q *Queries) DeleteRoutesForEvent(ctx context.Context, eventType string) error {
	_, err := q.db.ExecContext(ctx, deleteRoutesForEvent, eventType)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, "type", enabled, config, secret, created_at, updated_at
FROM notify_channels WHERE id = ?
`

func (q *Queries) GetChannel(ctx context.Context, id string) (*NotifyChannel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, id)
	var i NotifyChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Config,
		&i.Secret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, channel_id, event_type, severity, title, message,
    "status", attempts, last_error, created_at, next_attempt_at, delivered_at
FROM notify_deliveries WHERE id = ?
`

func (q *Queries) GetDelivery(ctx context.Context, id string) (*NotifyDelivery, error) {
	row := q.db.QueryRowContext(ctx, getDelivery, id)
	var i NotifyDelivery
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.EventType,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.NextAttemptAt,
		&i.DeliveredAt,
	)
	return &i, err
}

const getEventSeverityOverride = `-- name: GetEventSeverityOverride :one
SELECT severity FROM notify_event_severity WHERE event_type = ?
`

func (q *Queries) GetEventSeverityOverride(ctx context.Context, eventType string) (string, error) {
	row := q.db.QueryRowContext(ctx, getEventSeverityOverride, eventType)
	var severity string
	err := row.Scan(&severity)
	return severity, err
}

const getQuietHours = `-- name: GetQuietHours :one
SELECT id, enabled, start_time, end_time, updated_at FROM notify_quiet_hours WHERE id = 1
`

func (q *Queries) GetQuietHours(ctx context.Context) (*NotifyQuietHour, error) {
	row := q.db.QueryRowContext(ctx, getQuietHours)
	var i NotifyQuietHour
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.StartTime,
		&i.EndTime,
		&i.UpdatedAt,
	)
	return &i, err
}

const hasEncryptedNotifySecrets = `-- name: HasEncryptedNotifySecrets :one
SELECT EXISTS(SELECT 1 FROM notify_channels WHERE secret IS NOT NULL)
`

func (q *Queries) HasEncryptedNotifySecrets(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasEncryptedNotifySecrets)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertRoute = `-- name: InsertRoute :exec
INSERT INTO notify_routes (event_type, channel_id) VALUES (?, ?)
`

type InsertRouteParams struct {
	EventType string `json:"event_type"`
	ChannelID string `json:"channel_id"`
}

func (q *Queries) InsertRoute(ctx context.Context, arg InsertRouteParams) error {
	_, err := q.db.ExecContext(ctx, insertRoute, arg.EventType, arg.ChannelID)
	return err
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, event_type, severity, title, message, created_at, read_at
FROM notify_alerts
ORDER BY
    CASE WHEN read_at IS NULL THEN 0 ELSE 1 END ASC,
    created_at DESC
`

func (q *Queries) ListAlerts(ctx context.Context) ([]*NotifyAlert, error) {
	rows, err := q.db.QueryContext(ctx, listAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*NotifyAlert
	for rows.Next() {
		var i NotifyAlert
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRoutes = `-- name: ListAllRoutes :many
SELECT event_type, channel_id FROM notify_routes ORDER BY event_type ASC, channel_id ASC
`

func (q *Queries) ListAllRoutes(ctx context.Context) ([]*NotifyRoute, error) {
	rows, err := q.db.QueryContext(ctx, listAllRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*NotifyRoute
	for rows.Next() {
		var i NotifyRoute
		if err := rows.Scan(&i.EventType, &i.ChannelID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, "type", enabled, config, secret, created_at, updated_at
FROM notify_channels ORDER BY created_at ASC
`

func (q *Queries) ListChannels(ctx context.Context) ([]*NotifyChannel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*NotifyChannel
	for rows.Next() {
		var i NotifyChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.Config,
			&i.Secret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsForEvent = `-- name: ListChannelsForEvent :many
SELECT c.id, c.name, c."type", c.enabled, c.config, c.secret, c.created_at, c.updated_at
FROM notify_channels c
JOIN notify_routes r ON r.channel_id = c.id
WHERE r.event_type = ? AND c.enabled = 1
ORDER BY c.created_at ASC
`

func (q *Queries) ListChannelsForEvent(ctx context.Context, eventType string) ([]*NotifyChannel, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsForEvent, eventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*NotifyChannel
	for rows.Next() {
		var i NotifyChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.Config,
			&i.Secret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueDeliveries = `-- name: ListDueDeliveries :many
SELECT id, channel_id, event_type, severity, title, message,
    "status", attempts, last_error, created_at, next_attempt_at, delivered_at
FROM notify_deliveries
WHERE "status" = 'pending' AND next_attempt_at <= ?
ORDER BY next_attempt_at ASC
LIMIT ?2
`

type ListDueDeliveriesParams struct {
	NextAttemptAt string `json:"next_attempt_at"`
	RowLimit      int64  `json:"row_limit"`
}

func (q *Queries) ListDueDeliveries(ctx context.Context, arg ListDueDeliveriesParams) ([]*NotifyDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listDueDeliveries, arg.NextAttemptAt, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*NotifyDelivery
	for rows.Next() {
		var i NotifyDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.EventType,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.NextAttemptAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventSeverityOverrides = `-- name: ListEventSeverityOverrides :many
SELECT event_type, severity FROM notify_event_severity
`

func (q *Queries) ListEventSeverityOverrides(ctx context.Context) ([]*NotifyEventSeverity, error) {
	rows, err := q.db.QueryContext(ctx, listEventSeverityOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*NotifyEventSeverity
	for rows.Next() {
		var i NotifyEventSeverity
		if err := rows.Scan(&i.EventType, &i.Severity); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesForEvent = `-- name: ListRoutesForEvent :many
SELECT channel_id FROM notify_routes WHERE event_type = ? ORDER BY channel_id ASC
`

func (q *Queries) ListRoutesForEvent(ctx context.Context, eventType string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRoutesForEvent, eventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var channel_id string
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlertsReadByIDs = `-- name: MarkAlertsReadByIDs :execrows
UPDATE notify_alerts
SET read_at = ?
WHERE read_at IS NULL AND id IN (/*SLICE:ids*/?)
`

type MarkAlertsReadByIDsParams struct {
	ReadAt sql.NullString `json:"read_at"`
	Ids    []string       `json:"ids"`
}

func (q *Queries) MarkAlertsReadByIDs(ctx context.Context, arg MarkAlertsReadByIDsParams) (int64, error) {
	query := markAlertsReadByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ReadAt)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markAllAlertsRead = `-- name: MarkAllAlertsRead :execrows
UPDATE notify_alerts
SET read_at = ?
WHERE read_at IS NULL
`

func (q *Queries) MarkAllAlertsRead(ctx context.Context, readAt sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAllAlertsRead, readAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setQuietHours = `-- name: SetQuietHours :exec
INSERT INTO notify_quiet_hours (id, enabled, start_time, end_time, updated_at)
VALUES (1, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    enabled = excluded.enabled,
    start_time = excluded.start_time,
    end_time = excluded.end_time,
    updated_at = excluded.updated_at
`

type SetQuietHoursParams struct {
	Enabled   int64  `json:"enabled"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) SetQuietHours(ctx context.Context, arg SetQuietHoursParams) error {
	_, err := q.db.ExecContext(ctx, setQuietHours,
		arg.Enabled,
		arg.StartTime,
		arg.EndTime,
		arg.UpdatedAt,
	)
	return err
}

const updateChannel = `-- name: UpdateChannel :execrows
UPDATE notify_channels
SET name = ?, "type" = ?, enabled = ?, config = ?, secret = ?, updated_at = ?
WHERE id = ?
`

type UpdateChannelParams struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	Enabled   int64  `json:"enabled"`
	Config    string `json:"config"`
	Secret    []byte `json:"secret"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateChannel,
		arg.Name,
		arg.Type,
		arg.Enabled,
		arg.Config,
		arg.Secret,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDeliveryAttempt = `-- name: UpdateDeliveryAttempt :exec
UPDATE notify_deliveries
SET "status" = ?, attempts = ?, last_error = ?, next_attempt_at = ?, delivered_at = ?
WHERE id = ?
`

type UpdateDeliveryAttemptParams struct {
	Status        string         `json:"status"`
	Attempts      int64          `json:"attempts"`
	LastError     sql.NullString `json:"last_error"`
	NextAttemptAt string         `json:"next_attempt_at"`
	DeliveredAt   sql.NullString `json:"delivered_at"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateDeliveryAttempt(ctx context.Context, arg UpdateDeliveryAttemptParams) error {
	_, err := q.db.ExecContext(ctx, updateDeliveryAttempt,
		arg.Status,
		arg.Attempts,
		arg.LastError,
		arg.NextAttemptAt,
		arg.DeliveredAt,
		arg.ID,
	)
	return err
}

const upsertEventSeverity = `-- name: UpsertEventSeverity :exec
INSERT INTO notify_event_severity (event_type, severity) VALUES (?, ?)
ON CONFLICT (event_type) DO UPDATE SET severity = excluded.severity
`

type UpsertEventSeverityParams struct {
	EventType string `json:"event_type"`
	Severity  string `json:"severity"`
}

func (q *Queries) UpsertEventSeverity(ctx context.Context, arg UpsertEventSeverityParams) error {
	_, err := q.db.ExecContext(ctx, upsertEventSeverity, arg.EventType, arg.Severity)
	return err
}
