// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry_credentials.sql

package storedb

import (
	"context"
)

const deleteRegistryCredential = `-- name: DeleteRegistryCredential :execrows
DELETE FROM registry_credentials WHERE registry = ?
`

func (q *Queries) DeleteRegistryCredential(ctx context.Context, registry string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRegistryCredential, registry)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRegistryCredential = `-- name: GetRegistryCredential :one
SELECT registry, credential, updated_at FROM registry_credentials WHERE registry = ?
`

func (q *Queries) GetRegistryCredential(ctx context.Context, registry string) (*RegistryCredential, error) {
	row := q.db.QueryRowContext(ctx, getRegistryCredential, registry)
	var i RegistryCredential
	err := row.Scan(&i.Registry, &i.Credential, &i.UpdatedAt)
	return &i, err
}

const listRegistryCredentials = `-- name: ListRegistryCredentials :many
SELECT registry, credential, updated_at FROM registry_credentials ORDER BY registry ASC
`

func (q *Queries) ListRegistryCredentials(ctx context.Context) ([]*RegistryCredential, error) {
	rows, err := q.db.QueryContext(ctx, listRegistryCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RegistryCredential
	for rows.Next() {
		var i RegistryCredential
		if err := rows.Scan(&i.Registry, &i.Credential, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRegistryCredential = `-- name: UpsertRegistryCredential :exec

INSERT INTO registry_credentials (registry, credential, updated_at)
VALUES (?, ?, ?)
ON CONFLICT (registry) DO UPDATE SET
    credential = excluded.credential,
    updated_at = excluded.updated_at
`

type UpsertRegistryCredentialParams struct {
	Registry   string `json:"registry"`
	Credential []byte `json:"credential"`
	UpdatedAt  string `json:"updated_at"`
}

// sqlc input (#488): the credentials the container update check logs in to a
// registry with, generated into internal/store/db/ by `make gen`. Doc
// comments live on the Go wrapper in internal/store/registry_credentials.go.
func (q *Queries) UpsertRegistryCredential(ctx context.Context, arg UpsertRegistryCredentialParams) error {
	_, err := q.db.ExecContext(ctx, upsertRegistryCredential, arg.Registry, arg.Credential, arg.UpdatedAt)
	return err
}
