// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relocation.sql

package storedb

import (
	"context"
)

const deleteRelocationManifest = `-- name: DeleteRelocationManifest :exec

DELETE FROM relocation_manifest
`

// sqlc input (#194): typed Go query code for the relocation_manifest and
// relocation_removing_disks tables, generated into internal/store/db/ by
// `make gen`. Doc comments live on the hand-written Go wrapper in
// internal/parity/relocation_store.go instead.
func (q *Queries) DeleteRelocationManifest(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRelocationManifest)
	return err
}

const deleteRelocationRemovingDisks = `-- name: DeleteRelocationRemovingDisks :exec
DELETE FROM relocation_removing_disks
`

func (q *Queries) DeleteRelocationRemovingDisks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRelocationRemovingDisks)
	return err
}

const insertRelocationManifestEntry = `-- name: InsertRelocationManifestEntry :exec
INSERT INTO relocation_manifest (rel_path, size, mtime, source_disk, target_disk)
VALUES (?, ?, ?, ?, ?)
`

type InsertRelocationManifestEntryParams struct {
	RelPath    string `json:"rel_path"`
	Size       int64  `json:"size"`
	Mtime      string `json:"mtime"`
	SourceDisk string `json:"source_disk"`
	TargetDisk string `json:"target_disk"`
}

func (q *Queries) InsertRelocationManifestEntry(ctx context.Context, arg InsertRelocationManifestEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertRelocationManifestEntry,
		arg.RelPath,
		arg.Size,
		arg.Mtime,
		arg.SourceDisk,
		arg.TargetDisk,
	)
	return err
}

const insertRelocationRemovingDisk = `-- name: InsertRelocationRemovingDisk :exec
INSERT INTO relocation_removing_disks (mountpoint) VALUES (?)
`

func (q *Queries) InsertRelocationRemovingDisk(ctx context.Context, mountpoint string) error {
	_, err := q.db.ExecContext(ctx, insertRelocationRemovingDisk, mountpoint)
	return err
}

const listRelocationManifest = `-- name: ListRelocationManifest :many
SELECT rel_path, size, mtime, source_disk, target_disk
FROM relocation_manifest
ORDER BY id ASC
`

type ListRelocationManifestRow struct {
	RelPath    string `json:"rel_path"`
	Size       int64  `json:"size"`
	Mtime      string `json:"mtime"`
	SourceDisk string `json:"source_disk"`
	TargetDisk string `json:"target_disk"`
}

func (q *Queries) ListRelocationManifest(ctx context.Context) ([]*ListRelocationManifestRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelocationManifest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListRelocationManifestRow
	for rows.Next() {
		var i ListRelocationManifestRow
		if err := rows.Scan(
			&i.RelPath,
			&i.Size,
			&i.Mtime,
			&i.SourceDisk,
			&i.TargetDisk,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelocationRemovingDisks = `-- name: ListRelocationRemovingDisks :many
SELECT mountpoint FROM relocation_removing_disks ORDER BY mountpoint ASC
`

func (q *Queries) ListRelocationRemovingDisks(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRelocationRemovingDisks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var mountpoint string
		if err := rows.Scan(&mountpoint); err != nil {
			return nil, err
		}
		items = append(items, mountpoint)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
