// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: restore_drill.sql

package storedb

import (
	"context"
	"database/sql"
)

const getRestoreDrillResult = `-- name: GetRestoreDrillResult :one

SELECT ran_at, passed, error, destinations
FROM restore_drill_result
WHERE id = 1
`

type GetRestoreDrillResultRow struct {
	RanAt        string         `json:"ran_at"`
	Passed       int64          `json:"passed"`
	Error        sql.NullString `json:"error"`
	Destinations string         `json:"destinations"`
}

// sqlc input (#63): the last restore drill's result, generated into
// internal/store/db/ by `make gen`.
func (q *Queries) GetRestoreDrillResult(ctx context.Context) (*GetRestoreDrillResultRow, error) {
	row := q.db.QueryRowContext(ctx, getRestoreDrillResult)
	var i GetRestoreDrillResultRow
	err := row.Scan(
		&i.RanAt,
		&i.Passed,
		&i.Error,
		&i.Destinations,
	)
	return &i, err
}

const upsertRestoreDrillResult = `-- name: UpsertRestoreDrillResult :exec
INSERT INTO restore_drill_result (id, ran_at, passed, error, destinations)
VALUES (1, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    ran_at = excluded.ran_at,
    passed = excluded.passed,
    error = excluded.error,
    destinations = excluded.destinations
`

type UpsertRestoreDrillResultParams struct {
	RanAt        string         `json:"ran_at"`
	Passed       int64          `json:"passed"`
	Error        sql.NullString `json:"error"`
	Destinations string         `json:"destinations"`
}

func (q *Queries) UpsertRestoreDrillResult(ctx context.Context, arg UpsertRestoreDrillResultParams) error {
	_, err := q.db.ExecContext(ctx, upsertRestoreDrillResult,
		arg.RanAt,
		arg.Passed,
		arg.Error,
		arg.Destinations,
	)
	return err
}
