// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package storedb

import (
	"context"
)

const getScheduleChain = `-- name: GetScheduleChain :one

SELECT
    id,
    start_time,
    weekly_scrub_day,
    mover_enabled,
    diff_guard_enabled,
    sync_enabled,
    scrub_enabled,
    config_backup_enabled,
    updated_at
FROM schedule_chain
WHERE id = 1
`

// sqlc input (#197): typed Go query code for schedule_chain and
// schedule_jobs, generated into internal/store/db/ by `make gen`.
func (q *Queries) GetScheduleChain(ctx context.Context) (*ScheduleChain, error) {
	row := q.db.QueryRowContext(ctx, getScheduleChain)
	var i ScheduleChain
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.WeeklyScrubDay,
		&i.MoverEnabled,
		&i.DiffGuardEnabled,
		&i.SyncEnabled,
		&i.ScrubEnabled,
		&i.ConfigBackupEnabled,
		&i.UpdatedAt,
	)
	return &i, err
}

const getScheduleJob = `-- name: GetScheduleJob :one
SELECT job_id, enabled, frequency, start_time, updated_at
FROM schedule_jobs
WHERE job_id = ?
`

func (q *Queries) GetScheduleJob(ctx context.Context, jobID string) (*ScheduleJob, error) {
	row := q.db.QueryRowContext(ctx, getScheduleJob, jobID)
	var i ScheduleJob
	err := row.Scan(
		&i.JobID,
		&i.Enabled,
		&i.Frequency,
		&i.StartTime,
		&i.UpdatedAt,
	)
	return &i, err
}

const listScheduleJobs = `-- name: ListScheduleJobs :many
SELECT job_id, enabled, frequency, start_time, updated_at
FROM schedule_jobs
ORDER BY job_id ASC
`

func (q *Queries) ListScheduleJobs(ctx context.Context) ([]*ScheduleJob, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ScheduleJob
	for rows.Next() {
		var i ScheduleJob
		if err := rows.Scan(
			&i.JobID,
			&i.Enabled,
			&i.Frequency,
			&i.StartTime,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertScheduleChain = `-- name: UpsertScheduleChain :exec
INSERT INTO schedule_chain (
    id,
    start_time,
    weekly_scrub_day,
    mover_enabled,
    diff_guard_enabled,
    sync_enabled,
    scrub_enabled,
    config_backup_enabled,
    updated_at
) VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    start_time = excluded.start_time,
    weekly_scrub_day = excluded.weekly_scrub_day,
    mover_enabled = excluded.mover_enabled,
    diff_guard_enabled = excluded.diff_guard_enabled,
    sync_enabled = excluded.sync_enabled,
    scrub_enabled = excluded.scrub_enabled,
    config_backup_enabled = excluded.config_backup_enabled,
    updated_at = excluded.updated_at
`

type UpsertScheduleChainParams struct {
	StartTime           string `json:"start_time"`
	WeeklyScrubDay      int64  `json:"weekly_scrub_day"`
	MoverEnabled        int64  `json:"mover_enabled"`
	DiffGuardEnabled    int64  `json:"diff_guard_enabled"`
	SyncEnabled         int64  `json:"sync_enabled"`
	ScrubEnabled        int64  `json:"scrub_enabled"`
	ConfigBackupEnabled int64  `json:"config_backup_enabled"`
	UpdatedAt           string `json:"updated_at"`
}

func (q *Queries) UpsertScheduleChain(ctx context.Context, arg UpsertScheduleChainParams) error {
	_, err := q.db.ExecContext(ctx, upsertScheduleChain,
		arg.StartTime,
		arg.WeeklyScrubDay,
		arg.MoverEnabled,
		arg.DiffGuardEnabled,
		arg.SyncEnabled,
		arg.ScrubEnabled,
		arg.ConfigBackupEnabled,
		arg.UpdatedAt,
	)
	return err
}

const upsertScheduleJob = `-- name: UpsertScheduleJob :exec
INSERT INTO schedule_jobs (job_id, enabled, frequency, start_time, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (job_id) DO UPDATE SET
    enabled = excluded.enabled,
    frequency = excluded.frequency,
    start_time = excluded.start_time,
    updated_at = excluded.updated_at
`

type UpsertScheduleJobParams struct {
	JobID     string `json:"job_id"`
	Enabled   int64  `json:"enabled"`
	Frequency string `json:"frequency"`
	StartTime string `json:"start_time"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) UpsertScheduleJob(ctx context.Context, arg UpsertScheduleJobParams) error {
	_, err := q.db.ExecContext(ctx, upsertScheduleJob,
		arg.JobID,
		arg.Enabled,
		arg.Frequency,
		arg.StartTime,
		arg.UpdatedAt,
	)
	return err
}
