// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schema_info.sql

package storedb

import (
	"context"
	"database/sql"
)

const getSchemaMeta = `-- name: GetSchemaMeta :one

SELECT id, installation_id, created_at, hostname, timezone, backup_passphrase, update_channel, update_check_enabled, previous_version
FROM schema_info WHERE id = 1
`

// sqlc input (Q60): typed Go query code for schema.sql's tables, generated
// into internal/store/db/ by `make gen`. Nothing hand-writes that package.
func (q *Queries) GetSchemaMeta(ctx context.Context) (*SchemaInfo, error) {
	row := q.db.QueryRowContext(ctx, getSchemaMeta)
	var i SchemaInfo
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.CreatedAt,
		&i.Hostname,
		&i.Timezone,
		&i.BackupPassphrase,
		&i.UpdateChannel,
		&i.UpdateCheckEnabled,
		&i.PreviousVersion,
	)
	return &i, err
}

const hasEncryptedBackupPassphrase = `-- name: HasEncryptedBackupPassphrase :one
SELECT EXISTS(
    SELECT 1 FROM schema_info WHERE id = 1 AND backup_passphrase IS NOT NULL AND length(backup_passphrase) > 0
) AS has_encrypted_backup_passphrase
`

func (q *Queries) HasEncryptedBackupPassphrase(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasEncryptedBackupPassphrase)
	var has_encrypted_backup_passphrase bool
	err := row.Scan(&has_encrypted_backup_passphrase)
	return has_encrypted_backup_passphrase, err
}

const insertSchemaMeta = `-- name: InsertSchemaMeta :exec
INSERT INTO schema_info (id, installation_id, created_at) VALUES (1, ?, ?)
`

type InsertSchemaMetaParams struct {
	InstallationID string `json:"installation_id"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) InsertSchemaMeta(ctx context.Context, arg InsertSchemaMetaParams) error {
	_, err := q.db.ExecContext(ctx, insertSchemaMeta, arg.InstallationID, arg.CreatedAt)
	return err
}

const updateGeneralSettings = `-- name: UpdateGeneralSettings :exec
UPDATE schema_info
SET hostname = ?, timezone = ?, backup_passphrase = ?
WHERE id = 1
`

type UpdateGeneralSettingsParams struct {
	Hostname         sql.NullString `json:"hostname"`
	Timezone         sql.NullString `json:"timezone"`
	BackupPassphrase []byte         `json:"backup_passphrase"`
}

func (q *Queries) UpdateGeneralSettings(ctx context.Context, arg UpdateGeneralSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateGeneralSettings, arg.Hostname, arg.Timezone, arg.BackupPassphrase)
	return err
}

const updatePreviousVersion = `-- name: UpdatePreviousVersion :exec
UPDATE schema_info
SET previous_version = ?
WHERE id = 1
`

func (q *Queries) UpdatePreviousVersion(ctx context.Context, previousVersion sql.NullString) error {
	_, err := q.db.ExecContext(ctx, updatePreviousVersion, previousVersion)
	return err
}

const updateUpdateSettings = `-- name: UpdateUpdateSettings :exec
UPDATE schema_info
SET update_channel = ?, update_check_enabled = ?
WHERE id = 1
`

type UpdateUpdateSettingsParams struct {
	UpdateChannel      string `json:"update_channel"`
	UpdateCheckEnabled int64  `json:"update_check_enabled"`
}

func (q *Queries) UpdateUpdateSettings(ctx context.Context, arg UpdateUpdateSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateUpdateSettings, arg.UpdateChannel, arg.UpdateCheckEnabled)
	return err
}
