// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schema_info.sql

package storedb

import (
	"context"
)

const getSchemaMeta = `-- name: GetSchemaMeta :one

SELECT id, installation_id, created_at FROM schema_info WHERE id = 1
`

// sqlc input (Q60): typed Go query code for schema.sql's tables, generated
// into internal/store/db/ by `make gen`. Nothing hand-writes that package.
func (q *Queries) GetSchemaMeta(ctx context.Context) (*SchemaInfo, error) {
	row := q.db.QueryRowContext(ctx, getSchemaMeta)
	var i SchemaInfo
	err := row.Scan(&i.ID, &i.InstallationID, &i.CreatedAt)
	return &i, err
}

const insertSchemaMeta = `-- name: InsertSchemaMeta :exec
INSERT INTO schema_info (id, installation_id, created_at) VALUES (1, ?, ?)
`

type InsertSchemaMetaParams struct {
	InstallationID string `json:"installation_id"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) InsertSchemaMeta(ctx context.Context, arg InsertSchemaMetaParams) error {
	_, err := q.db.ExecContext(ctx, insertSchemaMeta, arg.InstallationID, arg.CreatedAt)
	return err
}
