// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package storedb

import (
	"context"
	"database/sql"
)

const deleteShare = `-- name: DeleteShare :execrows
DELETE FROM shares WHERE name = ?
`

func (q *Queries) DeleteShare(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteShare, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getShare = `-- name: GetShare :one
SELECT
    name, cache_mode, create_policy,
    smb_enabled, smb_guest, smb_read_only, smb_browseable,
    smb_recycle, smb_time_machine, smb_time_machine_max_size,
    nfs_enabled, nfs_hosts, nfs_squash,
    created_at, updated_at
FROM shares WHERE name = ?
`

func (q *Queries) GetShare(ctx context.Context, name string) (*Share, error) {
	row := q.db.QueryRowContext(ctx, getShare, name)
	var i Share
	err := row.Scan(
		&i.Name,
		&i.CacheMode,
		&i.CreatePolicy,
		&i.SmbEnabled,
		&i.SmbGuest,
		&i.SmbReadOnly,
		&i.SmbBrowseable,
		&i.SmbRecycle,
		&i.SmbTimeMachine,
		&i.SmbTimeMachineMaxSize,
		&i.NfsEnabled,
		&i.NfsHosts,
		&i.NfsSquash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertShare = `-- name: InsertShare :exec

INSERT INTO shares (
    name, cache_mode, create_policy,
    smb_enabled, smb_guest, smb_read_only, smb_browseable,
    smb_recycle, smb_time_machine, smb_time_machine_max_size,
    nfs_enabled, nfs_hosts, nfs_squash,
    created_at, updated_at
) VALUES (
    ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?, ?
)
`

type InsertShareParams struct {
	Name                  string         `json:"name"`
	CacheMode             string         `json:"cache_mode"`
	CreatePolicy          string         `json:"create_policy"`
	SmbEnabled            int64          `json:"smb_enabled"`
	SmbGuest              int64          `json:"smb_guest"`
	SmbReadOnly           int64          `json:"smb_read_only"`
	SmbBrowseable         int64          `json:"smb_browseable"`
	SmbRecycle            int64          `json:"smb_recycle"`
	SmbTimeMachine        int64          `json:"smb_time_machine"`
	SmbTimeMachineMaxSize sql.NullString `json:"smb_time_machine_max_size"`
	NfsEnabled            int64          `json:"nfs_enabled"`
	NfsHosts              string         `json:"nfs_hosts"`
	NfsSquash             string         `json:"nfs_squash"`
	CreatedAt             string         `json:"created_at"`
	UpdatedAt             string         `json:"updated_at"`
}

// sqlc input (#46): typed Go query code for the shares table, generated
// into internal/store/db/ by `make gen`. Deliberately no comment other
// than each "-- name:" line between queries below (see jobs.sql). Doc
// comments live on the hand-written Go wrapper in internal/store/share.go.
func (q *Queries) InsertShare(ctx context.Context, arg InsertShareParams) error {
	_, err := q.db.ExecContext(ctx, insertShare,
		arg.Name,
		arg.CacheMode,
		arg.CreatePolicy,
		arg.SmbEnabled,
		arg.SmbGuest,
		arg.SmbReadOnly,
		arg.SmbBrowseable,
		arg.SmbRecycle,
		arg.SmbTimeMachine,
		arg.SmbTimeMachineMaxSize,
		arg.NfsEnabled,
		arg.NfsHosts,
		arg.NfsSquash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listShares = `-- name: ListShares :many
SELECT
    name, cache_mode, create_policy,
    smb_enabled, smb_guest, smb_read_only, smb_browseable,
    smb_recycle, smb_time_machine, smb_time_machine_max_size,
    nfs_enabled, nfs_hosts, nfs_squash,
    created_at, updated_at
FROM shares
ORDER BY name ASC
`

func (q *Queries) ListShares(ctx context.Context) ([]*Share, error) {
	rows, err := q.db.QueryContext(ctx, listShares)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Share
	for rows.Next() {
		var i Share
		if err := rows.Scan(
			&i.Name,
			&i.CacheMode,
			&i.CreatePolicy,
			&i.SmbEnabled,
			&i.SmbGuest,
			&i.SmbReadOnly,
			&i.SmbBrowseable,
			&i.SmbRecycle,
			&i.SmbTimeMachine,
			&i.SmbTimeMachineMaxSize,
			&i.NfsEnabled,
			&i.NfsHosts,
			&i.NfsSquash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShare = `-- name: UpdateShare :execrows
UPDATE shares
SET cache_mode = ?, create_policy = ?,
    smb_enabled = ?, smb_guest = ?, smb_read_only = ?, smb_browseable = ?,
    smb_recycle = ?, smb_time_machine = ?, smb_time_machine_max_size = ?,
    nfs_enabled = ?, nfs_hosts = ?, nfs_squash = ?,
    updated_at = ?
WHERE name = ?
`

type UpdateShareParams struct {
	CacheMode             string         `json:"cache_mode"`
	CreatePolicy          string         `json:"create_policy"`
	SmbEnabled            int64          `json:"smb_enabled"`
	SmbGuest              int64          `json:"smb_guest"`
	SmbReadOnly           int64          `json:"smb_read_only"`
	SmbBrowseable         int64          `json:"smb_browseable"`
	SmbRecycle            int64          `json:"smb_recycle"`
	SmbTimeMachine        int64          `json:"smb_time_machine"`
	SmbTimeMachineMaxSize sql.NullString `json:"smb_time_machine_max_size"`
	NfsEnabled            int64          `json:"nfs_enabled"`
	NfsHosts              string         `json:"nfs_hosts"`
	NfsSquash             string         `json:"nfs_squash"`
	UpdatedAt             string         `json:"updated_at"`
	Name                  string         `json:"name"`
}

func (q *Queries) UpdateShare(ctx context.Context, arg UpdateShareParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateShare,
		arg.CacheMode,
		arg.CreatePolicy,
		arg.SmbEnabled,
		arg.SmbGuest,
		arg.SmbReadOnly,
		arg.SmbBrowseable,
		arg.SmbRecycle,
		arg.SmbTimeMachine,
		arg.SmbTimeMachineMaxSize,
		arg.NfsEnabled,
		arg.NfsHosts,
		arg.NfsSquash,
		arg.UpdatedAt,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
