// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share_usage.sql

package storedb

import (
	"context"
)

const deleteShareUsage = `-- name: DeleteShareUsage :exec

DELETE FROM share_usage
`

// sqlc input (#223): typed Go query code for the share_usage and
// share_usage_computed_at tables, generated into internal/store/db/ by
// `make gen`. Doc comments live on the hand-written Go wrapper in
// internal/parity/usage_store.go instead.
func (q *Queries) DeleteShareUsage(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteShareUsage)
	return err
}

const getShareUsageComputedAt = `-- name: GetShareUsageComputedAt :one
SELECT computed_at FROM share_usage_computed_at WHERE id = 1
`

func (q *Queries) GetShareUsageComputedAt(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getShareUsageComputedAt)
	var computed_at string
	err := row.Scan(&computed_at)
	return computed_at, err
}

const insertShareUsage = `-- name: InsertShareUsage :exec
INSERT INTO share_usage (share_name, disk_mountpoint, bytes)
VALUES (?, ?, ?)
`

type InsertShareUsageParams struct {
	ShareName      string `json:"share_name"`
	DiskMountpoint string `json:"disk_mountpoint"`
	Bytes          int64  `json:"bytes"`
}

func (q *Queries) InsertShareUsage(ctx context.Context, arg InsertShareUsageParams) error {
	_, err := q.db.ExecContext(ctx, insertShareUsage, arg.ShareName, arg.DiskMountpoint, arg.Bytes)
	return err
}

const listAllShareUsage = `-- name: ListAllShareUsage :many
SELECT share_name, disk_mountpoint, bytes
FROM share_usage
ORDER BY share_name ASC, disk_mountpoint ASC
`

func (q *Queries) ListAllShareUsage(ctx context.Context) ([]*ShareUsage, error) {
	rows, err := q.db.QueryContext(ctx, listAllShareUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ShareUsage
	for rows.Next() {
		var i ShareUsage
		if err := rows.Scan(&i.ShareName, &i.DiskMountpoint, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShareUsageByShare = `-- name: ListShareUsageByShare :many
SELECT share_name, disk_mountpoint, bytes
FROM share_usage
WHERE share_name = ?
ORDER BY disk_mountpoint ASC
`

func (q *Queries) ListShareUsageByShare(ctx context.Context, shareName string) ([]*ShareUsage, error) {
	rows, err := q.db.QueryContext(ctx, listShareUsageByShare, shareName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ShareUsage
	for rows.Next() {
		var i ShareUsage
		if err := rows.Scan(&i.ShareName, &i.DiskMountpoint, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertShareUsageComputedAt = `-- name: UpsertShareUsageComputedAt :exec
INSERT INTO share_usage_computed_at (id, computed_at) VALUES (1, ?)
ON CONFLICT (id) DO UPDATE SET computed_at = excluded.computed_at
`

func (q *Queries) UpsertShareUsageComputedAt(ctx context.Context, computedAt string) error {
	_, err := q.db.ExecContext(ctx, upsertShareUsageComputedAt, computedAt)
	return err
}
