// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spin_events.sql

package storedb

import (
	"context"
)

const countSpinEvents = `-- name: CountSpinEvents :one
SELECT COUNT(*) FROM spin_events
`

func (q *Queries) CountSpinEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpinEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertSpinEvent = `-- name: InsertSpinEvent :exec

INSERT INTO spin_events (device, from_state, to_state, at) VALUES (?, ?, ?, ?)
`

type InsertSpinEventParams struct {
	Device    string `json:"device"`
	FromState string `json:"from_state"`
	ToState   string `json:"to_state"`
	At        string `json:"at"`
}

// sqlc input (#110, Q60): typed Go query code for the spin_events table,
// generated into internal/store/db/ by `make gen`. Deliberately no
// comment other than each "-- name:" line between queries below (see
// jobs.sql for the same note about sqlc's SQLite engine).
func (q *Queries) InsertSpinEvent(ctx context.Context, arg InsertSpinEventParams) error {
	_, err := q.db.ExecContext(ctx, insertSpinEvent,
		arg.Device,
		arg.FromState,
		arg.ToState,
		arg.At,
	)
	return err
}

const listDailyWakeCounts = `-- name: ListDailyWakeCounts :many
SELECT device, date(at) AS day, COUNT(*) AS count
FROM spin_events
WHERE from_state = 'standby' AND to_state = 'active'
GROUP BY device, date(at)
ORDER BY day DESC, device
`

type ListDailyWakeCountsRow struct {
	Device string      `json:"device"`
	Day    interface{} `json:"day"`
	Count  int64       `json:"count"`
}

func (q *Queries) ListDailyWakeCounts(ctx context.Context) ([]*ListDailyWakeCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailyWakeCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDailyWakeCountsRow
	for rows.Next() {
		var i ListDailyWakeCountsRow
		if err := rows.Scan(&i.Device, &i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpinEvents = `-- name: ListSpinEvents :many
SELECT id, device, from_state, to_state, at
FROM spin_events
ORDER BY at DESC
`

func (q *Queries) ListSpinEvents(ctx context.Context) ([]*SpinEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSpinEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SpinEvent
	for rows.Next() {
		var i SpinEvent
		if err := rows.Scan(
			&i.ID,
			&i.Device,
			&i.FromState,
			&i.ToState,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneSpinEvents = `-- name: PruneSpinEvents :exec
DELETE FROM spin_events WHERE at < ?
`

func (q *Queries) PruneSpinEvents(ctx context.Context, at string) error {
	_, err := q.db.ExecContext(ctx, pruneSpinEvents, at)
	return err
}
