// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spin_events.sql

package storedb

import (
	"context"
)

const countSpinEvents = `-- name: CountSpinEvents :one
SELECT COUNT(*) FROM spin_events
`

func (q *Queries) CountSpinEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpinEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertSpinEvent = `-- name: InsertSpinEvent :exec

INSERT INTO spin_events (device, from_state, to_state, at) VALUES (?, ?, ?, ?)
`

type InsertSpinEventParams struct {
	Device    string `json:"device"`
	FromState string `json:"from_state"`
	ToState   string `json:"to_state"`
	At        string `json:"at"`
}

// sqlc input (#110, Q60): typed Go query code for the spin_events table,
// generated into internal/store/db/ by `make gen`. Deliberately no
// comment other than each "-- name:" line between queries below (see
// jobs.sql for the same note about sqlc's SQLite engine).
func (q *Queries) InsertSpinEvent(ctx context.Context, arg InsertSpinEventParams) error {
	_, err := q.db.ExecContext(ctx, insertSpinEvent,
		arg.Device,
		arg.FromState,
		arg.ToState,
		arg.At,
	)
	return err
}

const pruneSpinEvents = `-- name: PruneSpinEvents :exec
DELETE FROM spin_events WHERE at < ?
`

func (q *Queries) PruneSpinEvents(ctx context.Context, at string) error {
	_, err := q.db.ExecContext(ctx, pruneSpinEvents, at)
	return err
}
