// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stacks.sql

package storedb

import (
	"context"
)

const deleteStack = `-- name: DeleteStack :execrows
DELETE FROM stacks WHERE name = ?
`

func (q *Queries) DeleteStack(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteStack, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getStack = `-- name: GetStack :one
SELECT name, template_source, template_id, template_revision, compose, env, installed_at, manually_edited
FROM stacks WHERE name = ?
`

func (q *Queries) GetStack(ctx context.Context, name string) (*Stack, error) {
	row := q.db.QueryRowContext(ctx, getStack, name)
	var i Stack
	err := row.Scan(
		&i.Name,
		&i.TemplateSource,
		&i.TemplateID,
		&i.TemplateRevision,
		&i.Compose,
		&i.Env,
		&i.InstalledAt,
		&i.ManuallyEdited,
	)
	return &i, err
}

const insertStack = `-- name: InsertStack :exec

INSERT INTO stacks (name, template_source, template_id, template_revision, compose, env, installed_at, manually_edited)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertStackParams struct {
	Name             string `json:"name"`
	TemplateSource   string `json:"template_source"`
	TemplateID       string `json:"template_id"`
	TemplateRevision string `json:"template_revision"`
	Compose          string `json:"compose"`
	Env              []byte `json:"env"`
	InstalledAt      string `json:"installed_at"`
	ManuallyEdited   int64  `json:"manually_edited"`
}

// sqlc input (#278): the stacks table, generated into internal/store/db/ by
// `make gen`. Doc comments live on the Go wrapper in internal/store/stack.go.
func (q *Queries) InsertStack(ctx context.Context, arg InsertStackParams) error {
	_, err := q.db.ExecContext(ctx, insertStack,
		arg.Name,
		arg.TemplateSource,
		arg.TemplateID,
		arg.TemplateRevision,
		arg.Compose,
		arg.Env,
		arg.InstalledAt,
		arg.ManuallyEdited,
	)
	return err
}

const listStacks = `-- name: ListStacks :many
SELECT name, template_source, template_id, template_revision, compose, env, installed_at, manually_edited
FROM stacks ORDER BY name ASC
`

func (q *Queries) ListStacks(ctx context.Context) ([]*Stack, error) {
	rows, err := q.db.QueryContext(ctx, listStacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Stack
	for rows.Next() {
		var i Stack
		if err := rows.Scan(
			&i.Name,
			&i.TemplateSource,
			&i.TemplateID,
			&i.TemplateRevision,
			&i.Compose,
			&i.Env,
			&i.InstalledAt,
			&i.ManuallyEdited,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStackCompose = `-- name: UpdateStackCompose :execrows
UPDATE stacks SET compose = ?, manually_edited = ? WHERE name = ?
`

type UpdateStackComposeParams struct {
	Compose        string `json:"compose"`
	ManuallyEdited int64  `json:"manually_edited"`
	Name           string `json:"name"`
}

func (q *Queries) UpdateStackCompose(ctx context.Context, arg UpdateStackComposeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateStackCompose, arg.Compose, arg.ManuallyEdited, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateStackEnv = `-- name: UpdateStackEnv :execrows
UPDATE stacks SET env = ? WHERE name = ?
`

type UpdateStackEnvParams struct {
	Env  []byte `json:"env"`
	Name string `json:"name"`
}

func (q *Queries) UpdateStackEnv(ctx context.Context, arg UpdateStackEnvParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateStackEnv, arg.Env, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
