// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_checks.sql

package storedb

import (
	"context"
)

const deleteImageUpdateCheck = `-- name: DeleteImageUpdateCheck :exec
DELETE FROM image_update_checks WHERE image = ?
`

func (q *Queries) DeleteImageUpdateCheck(ctx context.Context, image string) error {
	_, err := q.db.ExecContext(ctx, deleteImageUpdateCheck, image)
	return err
}

const listImageUpdateChecks = `-- name: ListImageUpdateChecks :many
SELECT image, checked_at, status, kind, available_tag, message
FROM image_update_checks ORDER BY image ASC
`

func (q *Queries) ListImageUpdateChecks(ctx context.Context) ([]*ImageUpdateCheck, error) {
	rows, err := q.db.QueryContext(ctx, listImageUpdateChecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ImageUpdateCheck
	for rows.Next() {
		var i ImageUpdateCheck
		if err := rows.Scan(
			&i.Image,
			&i.CheckedAt,
			&i.Status,
			&i.Kind,
			&i.AvailableTag,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertImageUpdateCheck = `-- name: UpsertImageUpdateCheck :exec

INSERT INTO image_update_checks (image, checked_at, status, kind, available_tag, message)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (image) DO UPDATE SET
    checked_at = excluded.checked_at,
    status = excluded.status,
    kind = excluded.kind,
    available_tag = excluded.available_tag,
    message = excluded.message
`

type UpsertImageUpdateCheckParams struct {
	Image        string `json:"image"`
	CheckedAt    string `json:"checked_at"`
	Status       string `json:"status"`
	Kind         string `json:"kind"`
	AvailableTag string `json:"available_tag"`
	Message      string `json:"message"`
}

// sqlc input (#71): the last container update check's result per image,
// generated into internal/store/db/ by `make gen`. Doc comments live on the
// Go wrapper in internal/store/updates.go.
func (q *Queries) UpsertImageUpdateCheck(ctx context.Context, arg UpsertImageUpdateCheckParams) error {
	_, err := q.db.ExecContext(ctx, upsertImageUpdateCheck,
		arg.Image,
		arg.CheckedAt,
		arg.Status,
		arg.Kind,
		arg.AvailableTag,
		arg.Message,
	)
	return err
}
