// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ups.sql

package storedb

import (
	"context"
)

const deleteUPSConfig = `-- name: DeleteUPSConfig :exec
DELETE FROM ups_config WHERE id = 1
`

func (q *Queries) DeleteUPSConfig(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUPSConfig)
	return err
}

const getUPSConfig = `-- name: GetUPSConfig :one

SELECT id, connection, driver, port, monitor_password, network_host, network_port,
       network_ups_name, network_username, network_password, low_battery_percent,
       runtime_seconds, updated_at
FROM ups_config WHERE id = 1
`

// sqlc input (#249, Q60): typed Go query code for the ups_config table,
// generated into internal/store/db/ by `make gen`.
func (q *Queries) GetUPSConfig(ctx context.Context) (*UpsConfig, error) {
	row := q.db.QueryRowContext(ctx, getUPSConfig)
	var i UpsConfig
	err := row.Scan(
		&i.ID,
		&i.Connection,
		&i.Driver,
		&i.Port,
		&i.MonitorPassword,
		&i.NetworkHost,
		&i.NetworkPort,
		&i.NetworkUpsName,
		&i.NetworkUsername,
		&i.NetworkPassword,
		&i.LowBatteryPercent,
		&i.RuntimeSeconds,
		&i.UpdatedAt,
	)
	return &i, err
}

const hasEncryptedUPSSecrets = `-- name: HasEncryptedUPSSecrets :one
SELECT EXISTS(
    SELECT 1 FROM ups_config
    WHERE length(monitor_password) > 0 OR length(network_password) > 0
)
`

func (q *Queries) HasEncryptedUPSSecrets(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasEncryptedUPSSecrets)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listUPSSecrets = `-- name: ListUPSSecrets :many
SELECT 'monitor_password' AS col, monitor_password AS ciphertext FROM ups_config WHERE id = 1 AND length(monitor_password) > 0
UNION ALL
SELECT 'network_password' AS col, network_password AS ciphertext FROM ups_config WHERE id = 1 AND length(network_password) > 0
`

type ListUPSSecretsRow struct {
	Col        string `json:"col"`
	Ciphertext []byte `json:"ciphertext"`
}

func (q *Queries) ListUPSSecrets(ctx context.Context) ([]*ListUPSSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUPSSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListUPSSecretsRow
	for rows.Next() {
		var i ListUPSSecretsRow
		if err := rows.Scan(&i.Col, &i.Ciphertext); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUPSConfig = `-- name: UpsertUPSConfig :exec
INSERT INTO ups_config (
    id, connection, driver, port, monitor_password, network_host, network_port,
    network_ups_name, network_username, network_password, low_battery_percent,
    runtime_seconds, updated_at
) VALUES (
    1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (id) DO UPDATE SET
    connection = excluded.connection,
    driver = excluded.driver,
    port = excluded.port,
    monitor_password = excluded.monitor_password,
    network_host = excluded.network_host,
    network_port = excluded.network_port,
    network_ups_name = excluded.network_ups_name,
    network_username = excluded.network_username,
    network_password = excluded.network_password,
    low_battery_percent = excluded.low_battery_percent,
    runtime_seconds = excluded.runtime_seconds,
    updated_at = excluded.updated_at
`

type UpsertUPSConfigParams struct {
	Connection        string `json:"connection"`
	Driver            string `json:"driver"`
	Port              string `json:"port"`
	MonitorPassword   []byte `json:"monitor_password"`
	NetworkHost       string `json:"network_host"`
	NetworkPort       int64  `json:"network_port"`
	NetworkUpsName    string `json:"network_ups_name"`
	NetworkUsername   string `json:"network_username"`
	NetworkPassword   []byte `json:"network_password"`
	LowBatteryPercent int64  `json:"low_battery_percent"`
	RuntimeSeconds    int64  `json:"runtime_seconds"`
	UpdatedAt         string `json:"updated_at"`
}

func (q *Queries) UpsertUPSConfig(ctx context.Context, arg UpsertUPSConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertUPSConfig,
		arg.Connection,
		arg.Driver,
		arg.Port,
		arg.MonitorPassword,
		arg.NetworkHost,
		arg.NetworkPort,
		arg.NetworkUpsName,
		arg.NetworkUsername,
		arg.NetworkPassword,
		arg.LowBatteryPercent,
		arg.RuntimeSeconds,
		arg.UpdatedAt,
	)
	return err
}
