// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package storedb

import (
	"context"
	"database/sql"
)

const activateUserTOTP = `-- name: ActivateUserTOTP :execrows
UPDATE users
SET totp_secret = ?1, totp_confirmed_at = ?2,
    totp_last_step = ?3, totp_pending_secret = NULL
WHERE id = ?4 AND totp_pending_secret = ?5
`

type ActivateUserTOTPParams struct {
	Secret        []byte         `json:"secret"`
	ConfirmedAt   sql.NullString `json:"confirmed_at"`
	Step          int64          `json:"step"`
	ID            string         `json:"id"`
	PendingSecret []byte         `json:"pending_secret"`
}

func (q *Queries) ActivateUserTOTP(ctx context.Context, arg ActivateUserTOTPParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateUserTOTP,
		arg.Secret,
		arg.ConfirmedAt,
		arg.Step,
		arg.ID,
		arg.PendingSecret,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM users WHERE role = 'admin'
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec

INSERT INTO users (
    id, username, password_hash, role, totp_secret, totp_confirmed_at, totp_last_step, created_at, totp_pending_secret
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateUserParams struct {
	ID                string         `json:"id"`
	Username          string         `json:"username"`
	PasswordHash      string         `json:"password_hash"`
	Role              string         `json:"role"`
	TotpSecret        []byte         `json:"totp_secret"`
	TotpConfirmedAt   sql.NullString `json:"totp_confirmed_at"`
	TotpLastStep      int64          `json:"totp_last_step"`
	CreatedAt         string         `json:"created_at"`
	TotpPendingSecret []byte         `json:"totp_pending_secret"`
}

// sqlc input (#22, Q60): typed Go query code for the users table,
// generated into internal/store/db/ by `make gen`. Deliberately no
// comment other than each "-- name:" line between queries below, and no
// non-ASCII character anywhere in this file: sqlc v1.31.1's SQLite engine
// mis-slices the raw source once an extra comment line appears between
// two queries (see jobs.sql for that note) and, confirmed while writing
// this file, also once any comment anywhere in the file contains a
// multi-byte UTF-8 character (an em dash, in this case) before the last
// query -- its byte-length/rune-length mismatch throws off every later
// query's slice offset, corrupting the generated SQL text of every query
// that follows it, not just the one after the offending comment.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.TotpSecret,
		arg.TotpConfirmedAt,
		arg.TotpLastStep,
		arg.CreatedAt,
		arg.TotpPendingSecret,
	)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role, totp_secret, totp_confirmed_at, totp_last_step, created_at, totp_pending_secret, last_login_at, smb_credential_set_at
FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecret,
		&i.TotpConfirmedAt,
		&i.TotpLastStep,
		&i.CreatedAt,
		&i.TotpPendingSecret,
		&i.LastLoginAt,
		&i.SmbCredentialSetAt,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, totp_secret, totp_confirmed_at, totp_last_step, created_at, totp_pending_secret, last_login_at, smb_credential_set_at
FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecret,
		&i.TotpConfirmedAt,
		&i.TotpLastStep,
		&i.CreatedAt,
		&i.TotpPendingSecret,
		&i.LastLoginAt,
		&i.SmbCredentialSetAt,
	)
	return &i, err
}

const hasEncryptedTOTPSecrets = `-- name: HasEncryptedTOTPSecrets :one
SELECT EXISTS(SELECT 1 FROM users WHERE totp_secret IS NOT NULL OR totp_pending_secret IS NOT NULL)
`

func (q *Queries) HasEncryptedTOTPSecrets(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasEncryptedTOTPSecrets)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markUserSMBCredentialSet = `-- name: MarkUserSMBCredentialSet :exec
UPDATE users SET smb_credential_set_at = ?1 WHERE id = ?2
`

type MarkUserSMBCredentialSetParams struct {
	SmbCredentialSetAt sql.NullString `json:"smb_credential_set_at"`
	ID                 string         `json:"id"`
}

func (q *Queries) MarkUserSMBCredentialSet(ctx context.Context, arg MarkUserSMBCredentialSetParams) error {
	_, err := q.db.ExecContext(ctx, markUserSMBCredentialSet, arg.SmbCredentialSetAt, arg.ID)
	return err
}

const recordUserLogin = `-- name: RecordUserLogin :exec
UPDATE users SET last_login_at = ?1 WHERE id = ?2
`

type RecordUserLoginParams struct {
	LastLoginAt sql.NullString `json:"last_login_at"`
	ID          string         `json:"id"`
}

func (q *Queries) RecordUserLogin(ctx context.Context, arg RecordUserLoginParams) error {
	_, err := q.db.ExecContext(ctx, recordUserLogin, arg.LastLoginAt, arg.ID)
	return err
}

const setUserPendingTOTPSecret = `-- name: SetUserPendingTOTPSecret :exec
UPDATE users SET totp_pending_secret = ?1 WHERE id = ?2
`

type SetUserPendingTOTPSecretParams struct {
	PendingSecret []byte `json:"pending_secret"`
	ID            string `json:"id"`
}

func (q *Queries) SetUserPendingTOTPSecret(ctx context.Context, arg SetUserPendingTOTPSecretParams) error {
	_, err := q.db.ExecContext(ctx, setUserPendingTOTPSecret, arg.PendingSecret, arg.ID)
	return err
}

const updateUserTOTPLastStepIfNewer = `-- name: UpdateUserTOTPLastStepIfNewer :execrows
UPDATE users SET totp_last_step = ?1
WHERE id = ?2 AND totp_last_step < ?1
`

type UpdateUserTOTPLastStepIfNewerParams struct {
	Step int64  `json:"step"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateUserTOTPLastStepIfNewer(ctx context.Context, arg UpdateUserTOTPLastStepIfNewerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserTOTPLastStepIfNewer, arg.Step, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
