package config

import (
	"strings"
	"testing"
	"time"
)

func TestHeaderMatchesDoc01Format(t *testing.T) {
	generatedAt := time.Date(2026, 9, 14, 10, 33, 12, 0, time.UTC)
	got := Header("sync", 47, generatedAt)

	want := strings.Join([]string{
		"# ============================================================",
		"#  Generated by Hoserva — DO NOT EDIT",
		"#  Changes will be overwritten on the next configuration apply.",
		"#  Edit via the web UI or:  hoserva sync",
		"#  Generated: 2026-09-14T10:33:12Z   Config revision: 47",
		"# ============================================================",
		"",
	}, "\n")

	if got != want {
		t.Fatalf("Header mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestHeaderConvertsToUTC(t *testing.T) {
	loc := time.FixedZone("CEST", 2*60*60)
	local := time.Date(2026, 9, 14, 12, 33, 12, 0, loc)

	got := Header("sync", 1, local)

	if !strings.Contains(got, "Generated: 2026-09-14T10:33:12Z") {
		t.Fatalf("Header did not convert the timestamp to UTC:\n%s", got)
	}
}
