package config

import (
	"fmt"
	"strings"
	"time"
)

// headerRule is the doc 01 §2 header's top and bottom border, reproduced
// byte for byte — drift detection hashes the whole file, so the header's
// exact text is part of what a later Check compares against.
const headerRule = "# ============================================================"

// Header renders the doc 01 §2 banner every generated file carries: what
// wrote it, that hand edits are overwritten, how to change it instead, and
// the revision and timestamp a later drift check reasons about. command is
// the `hoserva <command>` line a user runs instead of hand-editing — for
// example "sync" or "share create".
func Header(command string, revision int, generatedAt time.Time) string {
	var b strings.Builder
	fmt.Fprintln(&b, headerRule)
	fmt.Fprintln(&b, "#  Generated by Hoserva — DO NOT EDIT")
	fmt.Fprintln(&b, "#  Changes will be overwritten on the next configuration apply.")
	fmt.Fprintf(&b, "#  Edit via the web UI or:  hoserva %s\n", command)
	fmt.Fprintf(&b, "#  Generated: %s   Config revision: %d\n", generatedAt.UTC().Format(time.RFC3339), revision)
	fmt.Fprintln(&b, headerRule)
	return b.String()
}
